dart-frog-dev/dart_frog

packages/dart_frog_cli/example/README.md
packages/dart_frog_cli/lib/dart_frog_cli.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): add example

chore(dart_frog_cli): add example

---

bricks/create_dart_frog/__brick__/pubspec.yaml
packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart

**READY**
- refactor(bricks): update create_dart_frog brick to use hosted dart_frog

refactor(bricks): update create_dart_frog brick to use hosted dart_frog

---

bricks/dart_frog_dev_server/hooks/pubspec.lock
bricks/dart_frog_dev_server/hooks/pubspec.yaml
packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart

**READY**
- refactor(bricks): update dev_server brick to use hosted dart_frog_gen

refactor(bricks): update dev_server brick to use hosted dart_frog_gen

---

bricks/dart_frog_prod_server/hooks/pubspec.lock
bricks/dart_frog_prod_server/hooks/pubspec.yaml
packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart

**READY**
- refactor(bricks): update prod_server brick to use hosted dart_frog_gen

refactor(bricks): update prod_server brick to use hosted dart_frog_gen

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
- chore(dart_frog_gen): v0.0.1-dev.3

chore(dart_frog_gen): v0.0.1-dev.3

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.0.1-dev.3

chore(dart_frog): v0.0.1-dev.3

---

packages/dart_frog_cli/lib/src/version.dart

**READY**
- fix(dart_frog_cli): version string

fix(dart_frog_cli): version string

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.0.1-dev.3

chore(dart_frog_cli): v0.0.1-dev.3

---

packages/dart_frog/lib/src/router.dart
packages/dart_frog/test/src/serve_test.dart

**READY**
- fix(dart_frog): support multiple routeNotFound.read calls (closes #27)

fix(dart_frog): support multiple routeNotFound.read calls

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.0.1-dev.4

chore(dart_frog): v0.0.1-dev.4

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/test/src/build_route_configuration_test.dart

**READY**
- fix(dart_frog_gen): append missing / prefix (closes #30)

fix(dart_frog_gen): append missing / prefix

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
- chore(dart_frog_gen): v0.0.1-dev.4

chore(dart_frog_gen): v0.0.1-dev.4

---

bricks/dart_frog_dev_server/hooks/pubspec.lock
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/pubspec.lock
bricks/dart_frog_prod_server/hooks/pubspec.yaml
packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart

**READY**
- chore(dart_frog_cli): upgrade to dart_frog_gen ^0.0.1-dev.4

chore(dart_frog_cli): upgrade to dart_frog_gen ^0.0.1-dev.4

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.0.1-dev.4

chore(dart_frog_cli): v0.0.1-dev.4

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/test/src/build_route_configuration_test.dart

**READY**
- fix(dart_frog_gen)!: use [...] instead of <...> for dynamic routes
- windows compatibility (related to #35, #36)
- aligns more closely with nextjs and sveltekit

fix(dart_frog_gen)!: use `[...]` instead of `<...>` for dynamic routes

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
- chore(dart_frog_gen): v0.0.2-dev.1

chore(dart_frog_gen): v0.0.2-dev.1

---

bricks/dart_frog_dev_server/hooks/pubspec.lock
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/pubspec.lock
bricks/dart_frog_prod_server/hooks/pubspec.yaml

**READY**
- refactor(bricks): upgrade to dart_frog_gen ^0.0.2-dev.1

refactor(bricks): upgrade to dart_frog_gen ^0.0.2-dev.1

---

packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart

**READY**
- refactor(dart_frog): update dev and prod server bundles

refactor(dart_frog)!: update dev and prod server bundles

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.0.2-dev.1

chore(dart_frog_cli): v0.0.2-dev.1

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/lib/src/path_to_route.dart
packages/dart_frog_gen/test/src/path_to_route_test.dart

**READY**
- fix(dart_frog_gen): windows route generation (closes #35)

fix(dart_frog_gen): windows route generation

---

bricks/dart_frog_prod_server/hooks/pre_gen.dart
bricks/dart_frog_prod_server/hooks/pubspec.lock
bricks/dart_frog_prod_server/hooks/pubspec.yaml

**READY**
- fix(bricks): windows prod build use copyPath (closes #36)

fix(bricks): windows prod build use copyPath

---

README.md

**READY**
- docs(README): add status code, json, and fun facts (closes #40)

docs(README): add status code, json, and fun facts

---

packages/dart_frog/lib/src/_internal.dart
packages/dart_frog/lib/src/request_logger.dart
packages/dart_frog/lib/src/shelf_adapters.dart
packages/dart_frog/test/src/shelf_adapters_test.dart

**READY**
- feat(dart_frog): add `fromShelfHandler` and `fromShelfMiddleware` adapters

feat(dart_frog): add fromShelfHandler and fromShelfMiddleware adapters

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/lib/src/response.dart
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.0.1-dev.5

chore(dart_frog): v0.0.1-dev.5

---

.github/workflows/dart_frog_gen.yaml

**READY**
- ci(dart_frog_gen): use very_good_workflows

ci(dart_frog_gen): use very_good_workflows

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.0.2-dev.3

chore(dart_frog_cli): v0.0.2-dev.3

---

bricks/dart_frog_prod_server/hooks/post_gen.dart
bricks/dart_frog_prod_server/hooks/pre_gen.dart
bricks/dart_frog_prod_server/hooks/pubspec.lock

**READY**
- chore(bricks): upgrade mason_logger in prod server brick

chore(bricks): upgrade mason_logger in prod server brick

---

bricks/dart_frog_dev_server/hooks/pubspec.lock

**READY**
- chore(bricks): upgrade dev server hook deps

chore(bricks): upgrade dev server hook deps

---

bricks/create_dart_frog/hooks/post_gen.dart

**READY**
- chore(bricks): update create hook to latest mason_logger

chore(bricks): update create hook to latest mason_logger

---

.github/workflows/dart_frog_cli.yaml
packages/dart_frog_cli/e2e/pubspec.yaml
packages/dart_frog_cli/e2e/test/dev_smoke_test.dart
packages/dart_frog_cli/e2e/test/helpers/dart_frog_create.dart
packages/dart_frog_cli/e2e/test/helpers/dart_frog_dev.dart
packages/dart_frog_cli/e2e/test/helpers/helpers.dart
packages/dart_frog_cli/e2e/test/helpers/kill_dart_frog_server.dart
packages/dart_frog_cli/e2e/test/helpers/test_server.dart
packages/dart_frog_cli/e2e/test/smoke_test.dart

**READY**
- test(dart_frog_cli): add e2e tests

test(dart_frog_cli): add e2e tests

---

.github/workflows/dart_frog_cli.yaml
packages/dart_frog_cli/e2e/pubspec.yaml
packages/dart_frog_cli/e2e/test/dart_frog_build_test.dart
packages/dart_frog_cli/e2e/test/helpers/dart_frog_build.dart
packages/dart_frog_cli/e2e/test/helpers/dart_frog_create.dart
packages/dart_frog_cli/e2e/test/helpers/helpers.dart
packages/dart_frog_cli/e2e/test/helpers/kill_dart_frog_server.dart

**READY**
- test(dart_frog_cli): dart_frog build e2e tests

test(dart_frog_cli): dart_frog build e2e tests

---

packages/dart_frog/lib/src/_internal.dart
packages/dart_frog/lib/src/http_method.dart
packages/dart_frog/lib/src/router.dart
packages/dart_frog/pubspec.yaml
packages/dart_frog/test/src/router_test.dart

**READY**
- feat(dart_frog): expand router http method support (part of #57)
- get, head, post, put, delete, options, patch

feat(dart_frog): expand router http method support

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.0.1-dev.6

chore(dart_frog): v0.0.1-dev.6

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.0.2-dev.4

chore(dart_frog_cli): v0.0.2-dev.4

---

README.md
ROADMAP.md
packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- feat: support custom ports via `--port`
```sh
dart_frog dev --port 3000
```

chore(dart_frog_cli): v0.0.2-dev.5

---

README.md

**READY**
Add blog and livestream links to the README

docs: update README with more links

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.0.2-dev.6

chore(dart_frog_cli): v0.0.2-dev.6

---

packages/dart_frog/lib/src/shelf_adapters.dart
packages/dart_frog/test/src/shelf_adapters_test.dart

**READY**
- feat(dart_frog): toShelfMiddleware/toShelfHandler adapters

feat(dart_frog): toShelfMiddleware/toShelfHandler adapters

---

.github/workflows/deploy.yaml

**READY**
- ci(docs): fix deploy

ci(docs): fix deploy

---

example/routes/count/_middleware.dart
example/routes/count/index.dart
example/test/routes/count/_middleware_test.dart
example/test/routes/count/index_test.dart

**READY**
- docs(example): add /count route (closes #96)

docs(example): add `/count` route

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/test/src/build_route_configuration_test.dart

**READY**
- feat(dart_frog_gen): add serveStaticFiles to RouteConfiguration

feat(dart_frog_gen): add serveStaticFiles to RouteConfiguration

---

packages/dart_frog/lib/dart_frog.dart
packages/dart_frog/lib/src/create_static_file_handler.dart
packages/dart_frog/pubspec.yaml
packages/dart_frog/test/src/create_static_file_handler_test.dart

**READY**
- feat(dart_frog): createStaticFileHandler

feat(dart_frog): createStaticFileHandler

---

.github/workflows/deploy.yaml

**READY**
- ci(deploy): add paths to deploy workflow

ci(deploy): add paths to deploy workflow

---

bricks/dart_frog_dev_server/__brick__/server.dart
bricks/dart_frog_dev_server/hooks/pre_gen.dart
bricks/dart_frog_dev_server/hooks/pubspec.yaml

**READY**
- feat(bricks): update dev server to dart_frog_gen 0.0.2-dev.3

feat(bricks): update dev server to dart_frog_gen 0.0.2-dev.3

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.0.1-dev.8

chore(dart_frog): v0.0.1-dev.8

---

bricks/dart_frog_prod_server/__brick__/build/bin/server.dart
bricks/dart_frog_prod_server/hooks/pubspec.yaml

**READY**
- feat(bricks): update prod server to dart_frog_gen 0.0.2-dev.3

feat(bricks): update prod server to dart_frog_gen 0.0.2-dev.3

---

example/routes/count/_middleware.dart
example/routes/count/index.dart
example/test/routes/count/_middleware_test.dart
example/test/routes/count/index_test.dart

**READY**
- docs(example): simplify /count implementation

docs(example): simplify /count implementation

---

docs/docusaurus.config.js

**READY**
- docs: add link to verygood.ventures in footer

docs: add link to verygood.ventures in footer

---

README.md

**READY**
- docs(README): remove redundant pub badge

docs(README): remove redundant pub badge

---

docs/docs/roadmap.md

**READY/IN DEVELOPMENT/HOLD**
Correcting few typos in roadmap.md

docs(roadmap): minor typo corrections

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
- chore(dart_frog_gen): v0.0.2-dev.4

chore(dart_frog_gen): v0.0.2-dev.4

---

bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/pubspec.yaml
packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart

**READY**
- fix(dart_frog_cli): upgrade bricks to dart_frog_gen ^0.0.2-dev.4

fix(dart_frog_cli): upgrade bricks to dart_frog_gen ^0.0.2-dev.4

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.0.2-dev.8

chore(dart_frog_cli): v0.0.2-dev.8

---

packages/dart_frog/lib/src/context.dart

**READY**
Fixes typo in error message printed when a request context can’t find a dependency for a particular type.

fix(dart_frog): provider StateError message typo

---

packages/dart_frog/lib/src/response.dart
packages/dart_frog/test/src/response_test.dart

**READY**
- fix(dart_frog): Response `json()` return `Object?`

fix(dart_frog): Response `json()` return `Object?`

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.0.1-dev.10

chore(dart_frog): v0.0.1-dev.10

---

.github/dependabot.yaml

**READY**
- ci: github actions + npm dependabot config

ci: github actions + npm dependabot config

---

docs/docusaurus.config.js
docs/src/pages/index.js

**READY**
- docs: seo optimizations

docs: seo optimizations

---

docs/docusaurus.config.js

**READY**
- docs: update baseUrl

docs: update docs site to dartfrog.vgv.dev

---

CNAME

docs: add CNAME

---

docs/docs/deploy/google-cloud-run.md

**READY**
When I copy the example command to deploy to cloud run and paste it directly into my terminal (after switching the square bracketed parameters), it fails to run (my terminal doesn't recognize the comments.
I propose we remove the comments in the example since:
1. We already have an explanation of the square brackets directly below
2. Everyone should be able to copy the command directly and have their API deploy

docs: cloud run deploy script fixes

---

packages/dart_frog_cli/lib/src/commands/dev/dev.dart

**READY**
- refactor(dart_frog_cli): remove redundant `dart:io` import

refactor(dart_frog_cli): remove redundant dart:io import

---

packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/test/src/commands/dev/dev_test.dart

**READY**
- feat(dart_frog_cli): avoid logging empty newlines

feat(dart_frog_cli): avoid logging empty newlines

---

docs/src/pages/index.js

**READY**
- docs: fix blog image aspect ratio

docs: fix blog image aspect ratio

---

docs/docs/deploy/aws-app-runner.md

**READY**
Adds documentation for deploying to [AWS App Runner](https://aws.amazon.com/apprunner/) in a similar format to the [Cloud Run docs](https://dartfrog.vgv.dev/docs/deploy/google-cloud-run)

feat(docs): add AWS app runner deployment docs

---

docs/docusaurus.config.js

**READY**
- docs: fix edit this page url

docs: fix edit this page url

---

docs/docusaurus.config.js

**READY**
- docs: fix GitHub link

docs: fix GitHub link

---

bricks/create_dart_frog/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/pubspec.yaml

**READY**
- chore(bricks): upgrade to mason ^0.1.0-dev.29

chore(bricks): upgrade to mason ^0.1.0-dev.29

---

packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): upgrade to mason ^0.1.0-dev.29

chore(dart_frog_cli): upgrade to mason ^0.1.0-dev.29

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/test/src/build_route_configuration_test.dart

**READY**
- refactor(dart_frog_gen): make buildRouteConfiguration relative to routes
- simplify tests
- internal implementation improvements/cleanup

refactor(dart_frog_gen): make buildRouteConfiguration relative to routes

---

docs/docusaurus.config.js

**READY**
- docs: add utm tags to vgv links

docs: add utm tags to vgv links

---

bricks/create_dart_frog/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/pubspec.yaml
packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): upgrade to mason 0.1.0-dev.30

chore(dart_frog_cli): upgrade to mason 0.1.0-dev.30

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/test/src/build_route_configuration_test.dart

**READY**
- feat(dart_frog_gen): include endpoints in RouteConfiguration (part of #133)

feat(dart_frog_gen): include endpoints in RouteConfiguration

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
- chore(dart_frog_gen): v0.0.2-dev.5

chore(dart_frog_gen): v0.0.2-dev.5

---

.github/workflows/dart_frog_dev_server.yaml
bricks/dart_frog_dev_server/hooks/.gitignore
bricks/dart_frog_dev_server/hooks/analysis_options.yaml
bricks/dart_frog_dev_server/hooks/pre_gen.dart
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/test/pre_gen_test.dart

**READY**
- feat(dart_frog_dev_server): report route conflicts

feat(dart_frog_dev_server): report route conflicts

---

.github/workflows/dart_frog_prod_server.yaml
bricks/dart_frog_prod_server/hooks/.gitignore
bricks/dart_frog_prod_server/hooks/analysis_options.yaml
bricks/dart_frog_prod_server/hooks/post_gen.dart
bricks/dart_frog_prod_server/hooks/pre_gen.dart
bricks/dart_frog_prod_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/test/pre_gen_test.dart

**READY**
- feat(dart_frog_prod_server): report route conflicts (closes #201)

feat(dart_frog_prod_server): report route conflicts

---

.github/workflows/dart_frog_prod_server.yaml
bricks/dart_frog_prod_server/hooks/post_gen.dart
bricks/dart_frog_prod_server/hooks/test/post_gen_test.dart

**READY**
- test(dart_frog_prod_server): post_gen.dart tests

test(dart_frog_prod_server): post_gen tests

---

.github/workflows/create_dart_frog.yaml
bricks/create_dart_frog/hooks/.gitignore
bricks/create_dart_frog/hooks/analysis_options.yaml
bricks/create_dart_frog/hooks/post_gen.dart
bricks/create_dart_frog/hooks/pubspec.yaml
bricks/create_dart_frog/hooks/test/post_gen_test.dart

**READY**
- test(create_dart_frog): post_gen tests

test(create_dart_frog): post_gen tests

---

.github/workflows/dart_frog_gen.yaml
packages/dart_frog_gen/lib/src/build_route_configuration.dart

**READY**
- fix(dart_frog_gen): windows relative import syntax

fix(dart_frog_gen): windows relative import syntax

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
- chore(dart_frog_gen): v0.0.2-dev.6

chore(dart_frog_gen): v0.0.2-dev.6

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- feat: report route conflicts during `dart_frog dev`
- feat: report route conflicts during `dart_frog build`
- feat: avoid logging empty newlines during `dart_frog dev`
- chore: upgrade to `mason ^0.1.0-dev.31`
- chore: upgrade to `dart_frog_gen ^0.0.2-dev.6`
- docs: pubspec `homepage`, `repository`, `issue_tracker`, and `documentation` links

chore(dart_frog_cli): v0.0.2-dev.9

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- fix: Request/Response `headers` is of type `Map<String, String>`
- docs: pubspec `homepage`, `repository`, `issue_tracker`, and `documentation` links

chore(dart_frog): v0.0.1-dev.11

---

docs/docs/deploy/digital-ocean-app-platform.md

**READY**
Adds a page to the docs for deploying to [Digital Ocean App Platform](https://www.digitalocean.com/products/app-platform).

docs(deploy): add digital ocean

---

docs/src/pages/index.js

**READY**
- docs: update homepage video link to Dart Frog playlist

docs: update homepage video link to Dart Frog playlist

---

packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/test/src/commands/dev/dev_test.dart

**READY**
- fix(dart_frog_cli): kill process on windows on sigint

fix(dart_frog_cli): kill process on windows on sigint

---

packages/dart_frog_cli/lib/src/command_runner.dart
packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
packages/dart_frog_cli/pubspec.yaml
packages/dart_frog_cli/test/src/command_runner_test.dart
packages/dart_frog_cli/test/src/commands/dev/dev_test.dart

**READY**
- feat(dart_frog_cli): improve hot reload reporting and error recovery #185
- feat(dart_frog_cli): add `--verbose` flag to `dev` command

feat(dart_frog_cli): improve hot reload reporting and error recovery

---

packages/dart_frog_cli/lib/src/command_runner.dart
packages/dart_frog_cli/lib/src/commands/build/build.dart
packages/dart_frog_cli/lib/src/commands/create/create.dart
packages/dart_frog_cli/test/src/command_runner_test.dart

**READY**
- feat(dart_frog_cli): add verbose logs for build and create commands

feat(dart_frog_cli): add verbose logs for build and create commands

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- feat: improve hot reload error reporting/recovery
- eliminate duplicate error logs
- improve error reporting
- hot reload reliability improvements on windows
- feat: add `--verbose` flag
- fix: kill process on windows on sigint
- `"port is already in use"` after terminating the process

chore(dart_frog_cli): v0.0.2-dev.10

---

.github/workflows/examples_counter.yaml
examples/counter/.gitignore
examples/counter/README.md
examples/counter/analysis_options.yaml
examples/counter/pubspec.yaml
examples/counter/routes/_middleware.dart
examples/counter/routes/index.dart
examples/counter/test/routes/_middleware_test.dart
examples/counter/test/routes/index_test.dart

**READY**
- docs(examples): add counter example

docs(examples): add counter example

---

.github/workflows/examples_echo.yaml
examples/echo/.gitignore
examples/echo/README.md
examples/echo/analysis_options.yaml
examples/echo/pubspec.yaml
examples/echo/routes/[message].dart
examples/echo/test/routes/[message]_test.dart

**READY**
- docs(examples): add echo example

docs(examples): add echo example

---

.github/workflows/examples_todos.yaml
examples/todos/.gitignore
examples/todos/README.md
examples/todos/analysis_options.yaml
examples/todos/packages/in_memory_todos_data_source/.gitignore
examples/todos/packages/in_memory_todos_data_source/README.md
examples/todos/packages/in_memory_todos_data_source/analysis_options.yaml
examples/todos/packages/in_memory_todos_data_source/coverage_badge.svg
examples/todos/packages/in_memory_todos_data_source/lib/in_memory_todos_data_source.dart
examples/todos/packages/in_memory_todos_data_source/lib/src/in_memory_todos_data_source.dart
examples/todos/packages/in_memory_todos_data_source/pubspec.yaml
examples/todos/packages/in_memory_todos_data_source/test/src/in_memory_todos_data_source_test.dart
examples/todos/packages/todos_data_source/.gitignore
examples/todos/packages/todos_data_source/README.md
examples/todos/packages/todos_data_source/analysis_options.yaml
examples/todos/packages/todos_data_source/coverage_badge.svg
examples/todos/packages/todos_data_source/lib/src/models/models.dart
examples/todos/packages/todos_data_source/lib/src/models/todo.dart
examples/todos/packages/todos_data_source/lib/src/models/todo.g.dart
examples/todos/packages/todos_data_source/lib/src/todos_data_source.dart
examples/todos/packages/todos_data_source/lib/todos_data_source.dart
examples/todos/packages/todos_data_source/pubspec.yaml
examples/todos/packages/todos_data_source/test/src/models/todo_test.dart
examples/todos/packages/todos_data_source/test/src/todos_data_source_test.dart
examples/todos/pubspec.yaml
examples/todos/routes/_middleware.dart
examples/todos/routes/todos/[id].dart
examples/todos/routes/todos/index.dart
examples/todos/test/routes/todos/[id]_test.dart
examples/todos/test/routes/todos/index_test.dart

**READY**
- docs(examples): add todos example

docs(examples): add todos example

---

docs/docs/basics/_category_.json
docs/docs/deploy/_category_.json
docs/docs/overview.md
docs/docs/roadmap.md
docs/docs/tutorials/_category_.json
docs/docs/tutorials/hello_world.md
docs/docusaurus.config.js
docs/package.json
docs/src/pages/index.js
docs/yarn.lock

**READY**
- docs(hello_world): create tutorial

docs(hello_world): create tutorial

---

docs/docs/tutorials/echo.md
docs/docs/tutorials/hello_world.md

**READY**
- docs(echo): create tutorial

docs(echo): create tutorial

---

docs/docs/tutorials/counter.md
docs/docs/tutorials/echo.md
docs/docs/tutorials/hello_world.md

**READY**
- docs(counter): create tutorial

docs(counter): create tutorial

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/test/src/build_route_configuration_test.dart

**READY**
- fix(dart_frog_gen): support repeated nested routes (part of #244)

fix(dart_frog_gen): support repeated nested routes

---

examples/counter/README.md
examples/echo/README.md
examples/hello_world/README.md
examples/todos/README.md

**READY**
- docs(examples): add "Powered by Dart Frog" badge

docs(examples): add "Powered by Dart Frog" badge

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/test/src/build_route_configuration_test.dart

**READY**
- fix(dart_frog_gen): detect rogue routes (part of #244)

fix(dart_frog_gen): detect rogue routes

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
- chore(dart_frog_gen): v0.0.2-dev.7

chore(dart_frog_gen): v0.0.2-dev.7

---

docs/docs/basics/routes.md

**READY**
- docs(routes): add route conflicts and rogue routes section

docs(routes): add route conflicts and rogue routes section

---

docs/docs/tutorials/counter.md
docs/docs/tutorials/todos.md
docs/docusaurus.config.js

**READY**
- docs(todos): create tutorial

docs(todos): create tutorial

---

bricks/dart_frog_dev_server/hooks/pre_gen.dart
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/test/pre_gen_test.dart

**READY**
- feat(dart_frog_dev_server): report rogue routes (closes #244)

feat(dart_frog_dev_server): report rogue routes

---

docs/docs/tutorials/counter.md

**READY**
- docs(counter): fix typo

docs(counter): fix typo

---

bricks/create_dart_frog/__brick__/README.md

**READY**
- chore(create_dart_frog): add "Powered by Dart Frog" badge to README

chore(create_dart_frog): add "Powered by Dart Frog" badge to README

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- fix: nested, repeated routes are supported
```
├── routes
│   ├── example
│   │   └── example.dart
```
- feat: `dart_frog create` adds "Powered by Dart Frog" badge to `README.md`
- feat: `dart_frog dev` reports rogue routes
- feat: `dart_frog build` reports rogue routes

chore(dart_frog_cli): v0.0.2-dev.11

---

examples/counter/pubspec_overrides.yaml
examples/echo/pubspec_overrides.yaml
examples/hello_world/pubspec_overrides.yaml
examples/todos/pubspec_overrides.yaml

**READY**
- chore(examples): add pubspec_overrides

chore(examples): add pubspec_overrides

---

packages/dart_frog_cli/e2e/test/helpers/dart_frog_dev.dart

**READY**
- chore(dart_frog_cli): fix analysis warning in e2e tests

chore(dart_frog_cli): fix analysis warning in e2e tests

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/test/src/build_route_configuration_test.dart

**READY**
- fix(dart_frog_gen): do not report rogue route if index.dart exists

fix(dart_frog_gen): do not report rogue route if index.dart exists

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/test/src/build_route_configuration_test.dart

**READY**
- feat(dart_frog_gen): add invokeCustomEntrypoint to RouteConfiguration
- part of #226

feat(dart_frog_gen): add invokeCustomEntrypoint to RouteConfiguration

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart

**READY**
- refactor(dart_frog_gen): improved readability

refactor(dart_frog_gen): improved readability

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
- chore(dart_frog_gen): v0.0.2-dev.8

chore(dart_frog_gen): v0.0.2-dev.8

---

bricks/dart_frog_dev_server/__brick__/server.dart
bricks/dart_frog_dev_server/hooks/pre_gen.dart
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/test/pre_gen_test.dart

**READY**
- feat(dart_frog_dev_server): upgrade to dart_frog_gen v0.0.2-dev.8
- feat(dart_frog_dev_server): support custom entrypoint (part of #226)

feat(dart_frog_dev_server): upgrade to dart_frog_gen v0.0.2-dev.8

---

bricks/dart_frog_prod_server/__brick__/build/bin/server.dart
bricks/dart_frog_prod_server/hooks/pre_gen.dart
bricks/dart_frog_prod_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/test/pre_gen_test.dart

**READY**
- feat(dart_frog_prod_server): upgrade to `dart_frog_gen ^0.0.2-dev.8`
- feat(dart_frog_prod_server): support custom entrypoint (part of #226)

feat(dart_frog_prod_server): support custom entrypoint

---

packages/dart_frog/lib/src/request.dart
packages/dart_frog/test/src/serve_test.dart

**READY**
- feat(dart_frog): expose HttpConnectionInfo on Request (closes #203)

feat(dart_frog): expose HttpConnectionInfo on Request

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.0.1-dev.12

chore(dart_frog): v0.0.1-dev.12

---

docs/docs/basics/dependency-injection.md

**READY**
- docs: enhance provider documentation

docs: enhance provider documentation

---

docs/docs/advanced/_category_.json
docs/docs/advanced/custom_entrypoint.md

**READY**
- docs: custom server entrypoint

docs: custom server entrypoint

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.0.2-dev.12

chore(dart_frog_cli): v0.0.2-dev.12

---

docs/docusaurus.config.js

**READY**
- docs: add advanced footer and navbar links

docs: add advanced footer and navbar links

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/README.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.1.0

chore(dart_frog): v0.1.0

---

bricks/create_dart_frog/__brick__/pubspec.yaml
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/pubspec.yaml

**READY**
- chore(bricks): upgrade to dart_frog v0.1.0

chore(bricks): upgrade to dart_frog v0.1.0

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/README.md
packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.1.0

chore(dart_frog_cli): v0.1.0

---

README.md
docs/docusaurus.config.js
packages/dart_frog_cli/README.md

**READY**
- docs: remove experimental warning

docs: remove experimental warning

---

README.md

**READY**
- docs(README): update status badge

docs(README): update status badge

---

docs/src/pages/index.js

**READY**
- docs: add stable release blog to homepage

docs: add stable release blog to homepage

---

bricks/dart_frog_prod_server/hooks/pre_gen.dart

**READY**
- fix(dart_frog_prod_server): windows build (closes #207)

fix(dart_frog_prod_server): windows build

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.1.1

chore(dart_frog_cli): v0.1.1

---

bricks/dart_frog_prod_server/hooks/pre_gen.dart
bricks/dart_frog_prod_server/hooks/test/pre_gen_test.dart

**READY**
- fix(dart_frog_prod_server): retain serveStaticAssets (closes #298)

fix(dart_frog_prod_server): retain serveStaticAssets

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.1.2

chore(dart_frog_cli): v0.1.2

---

.github/workflows/examples_counter.yaml
.github/workflows/examples_echo.yaml
.github/workflows/examples_hello_world.yaml
.github/workflows/examples_todos.yaml

**READY**
- Makes workflows for example projects to depend on dart_frog when:
- changes inside the library  (/lib/**)
- changes in its dependencies (pubspec.yaml)

ci: make examples workflow depend on dart frog

---

docs/docs/basics/routes.md

**READY**
- docs(routes): add warning about build_runner and using lib

docs(routes): add warning about build_runner and using lib

---

docs/docs/basics/routes.md

**READY**
- docs(routes): expand on request/response APIs (closes #322)

docs(routes): expand on request/response APIs

---

packages/dart_frog_cli/e2e/test/dart_frog_build_test.dart
packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/test/src/commands/dev/dev_test.dart

**READY**
- fix(dart_frog_cli): avoid generating an empty .dart_frog directory

fix(dart_frog_cli): avoid generating an empty .dart_frog directory

---

packages/dart_frog_cli/lib/src/command_runner.dart

READY
On line 54, changed to $packageName

refactor(dart_frog_cli): use packageName

---

packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- feat(dart_frog_cli): use new link api from mason_logger

feat(dart_frog_cli): use new link api from mason_logger

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.1.3

chore(dart_frog_cli): v0.1.3

---

bricks/create_dart_frog/__brick__/analysis_options.yaml
bricks/create_dart_frog/__brick__/pubspec.yaml

**READY**
- feat(create_dart_frog): upgrade to Dart 2.18 and Very Good Analysis 3.1.0

feat(create_dart_frog): upgrade to Dart 2.18 and Very Good Analysis 3.1.0

---

packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart

**READY**
- feat(dart_frog_cli): upgrade create bundle

feat(dart_frog_cli): upgrade create bundle

---

packages/dart_frog/lib/src/response.dart
packages/dart_frog/test/src/response_test.dart

**READY**
- fix(dart_frog): update Response.json headers to <String, Object>
- this was previously inconsistent with the default constructor types

fix(dart_frog): update Response.json headers to <String, Object>

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.1.1

chore(dart_frog): v0.1.1

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.1.4

chore(dart_frog_cli): v0.1.4

---

docs/docs/basics/serving-static-files.md

**READY**
- docs: use a custom directory for serving static files (https://github.com/VeryGoodOpenSource/dart_frog/issues/309)

docs: use a custom directory for serving static files

---

packages/dart_frog/lib/src/serve.dart
packages/dart_frog/pubspec.yaml
packages/dart_frog/test/src/serve_test.dart

**READY**
- feat(dart_frog): add x-powered-by-header to serve (closes #336)

feat(dart_frog): add x-powered-by-header to serve

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.1.2

chore(dart_frog): v0.1.2

---

bricks/dart_frog_dev_server/hooks/pre_gen.dart
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/test/pre_gen_test.dart

**READY**
- feat(dart_frog_dev): report external path dependencies
- part of #304

feat(dart_frog_dev): report external path dependencies

---

bricks/dart_frog_prod_server/hooks/pre_gen.dart
bricks/dart_frog_prod_server/hooks/test/pre_gen_test.dart

**READY**
- feat(dart_frog_prod): detect external path dependencies
- part of #304

feat(dart_frog_prod): detect external path dependencies

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.1.5

chore(dart_frog_cli): v0.1.5

---

docs/docs/advanced/powered_by_header.md

**READY**
- docs(advanced): powered by header

docs(advanced): powered by header

---

packages/dart_frog_cli/README.md
packages/dart_frog_cli/lib/src/command_runner.dart
packages/dart_frog_cli/lib/src/commands/update/update.dart
packages/dart_frog_cli/pubspec.yaml
packages/dart_frog_cli/test/src/command_runner_test.dart
packages/dart_frog_cli/test/src/commands/update/update_test.dart

**READY**
- feat(dart_frog_cli): update prompt and command

feat(dart_frog_cli): update prompt and command

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.1.6

chore(dart_frog_cli): v0.1.6

---

bricks/dart_frog_prod_server/__brick__/build/Dockerfile

**READY**
- fix(dart_frog_prod_server): copy static assets into docker image (part of #351)

fix(dart_frog_prod_server): copy static assets into docker image

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.1.7

chore(dart_frog_cli): v0.1.7

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.1.8

chore(dart_frog_cli): v0.1.8

---

.github/cspell.json
.github/workflows/main.yaml
bricks/create_dart_frog/brick.yaml
docs/docs/deploy/aws-app-runner.md
docs/docs/deploy/digital-ocean-app-platform.md
docs/docs/deploy/google-cloud-run.md
packages/dart_frog/lib/src/router.dart
packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart

**READY**
- ci: add spell check workflow

ci: add spell check workflow

---

.github/workflows/examples_counter.yaml
.github/workflows/examples_echo.yaml
.github/workflows/examples_hello_world.yaml
.github/workflows/examples_todos.yaml
docs/docs/overview.md
examples/counter/pubspec.yaml
examples/echo/pubspec.yaml
examples/hello_world/pubspec.yaml
examples/todos/pubspec.yaml
packages/dart_frog_cli/lib/src/commands/build/build.dart
packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/lib/src/runtime_compatibility.dart
packages/dart_frog_cli/pubspec.yaml
packages/dart_frog_cli/test/src/commands/build/build_test.dart
packages/dart_frog_cli/test/src/commands/dev/dev_test.dart
packages/dart_frog_cli/test/src/runtime_compatibility_test.dart

**READY**
- feat(dart_frog_cli): package:dart_frog runtime compatibility check

feat(dart_frog_cli): package:dart_frog runtime compatibility check

---

packages/dart_frog_cli/lib/src/command_runner.dart
packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/test/src/command_runner_test.dart
packages/dart_frog_cli/test/src/commands/dev/dev_test.dart

**READY**
- fix(dart_frog_cli): run update check on sigint

fix(dart_frog_cli): run update check on sigint

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.1.9

chore(dart_frog_cli): v0.1.9

---

docs/docs/basics/testing.md

**READY**
- docs(testing): include middleware tests

docs(testing): include middleware tests

---

.github/dependabot.yaml

READY
Running [this](https://github.com/renancaraujo/dependabot_gen) here added some more entries on

feat: update dependabot

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
- chore(dart_frog_gen): v0.2.0

chore(dart_frog_gen): v0.2.0

---

bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/test/pre_gen_test.dart

**READY**
- feat(dart_frog_dev_server): upgrade to `dart_frog_gen ^0.2.0`

feat(dart_frog_dev_server): upgrade to dart_frog_gen ^0.2.0

---

bricks/dart_frog_prod_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/test/pre_gen_test.dart

**READY**
- feat(dart_frog_prod_server): upgrade to dart_frog_gen ^0.2.0

feat(dart_frog_prod_server): upgrade to dart_frog_gen ^0.2.0

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.2.0

chore(dart_frog): v0.2.0

---

bricks/create_dart_frog/__brick__/pubspec.yaml

**READY**
- feat(create_dart_frog): upgrade to dart_frog ^0.2.0

feat(create_dart_frog): upgrade to dart_frog ^0.2.0

---

examples/counter/pubspec.yaml
examples/echo/pubspec.yaml
examples/hello_world/pubspec.yaml
examples/todos/pubspec.yaml
packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
packages/dart_frog_cli/lib/src/runtime_compatibility.dart
packages/dart_frog_cli/test/src/runtime_compatibility_test.dart

**READY**
- feat(dart_frog_cli): require dart_frog ^0.2.0

feat(dart_frog_cli): require dart_frog ^0.2.0

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.2.0

chore(dart_frog_cli): v0.2.0

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/test/src/build_route_configuration_test.dart
packages/dart_frog_gen/test/src/route_directory_test.dart

**READY**
- fix(dart_frog_gen)!: support cascading middleware (closes #382)

fix(dart_frog_gen)!: cascading middleware

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
- chore(dart_frog_gen): v0.3.0

chore(dart_frog_gen): v0.3.0

---

bricks/dart_frog_dev_server/__brick__/server.dart
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/test/pre_gen_test.dart
bricks/dart_frog_prod_server/__brick__/build/bin/server.dart
bricks/dart_frog_prod_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/test/pre_gen_test.dart

**READY**
- feat: upgrade bricks to dart_frog_gen ^0.3.0

feat: upgrade bricks to dart_frog_gen ^0.3.0

---

bricks/dart_frog_prod_server/__brick__/build/bin/server.dart

**READY**
- feat(dart_frog_prod_server): add startup log (closes #361)

feat(dart_frog_prod_server): add startup log

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.2.1

chore(dart_frog_cli): v0.2.1

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.2.2

chore(dart_frog_cli): v0.2.2

---

docs/package.json
docs/yarn.lock

**READY**
- chore(deps): upgrade to docusaurus 2.2.0

chore(deps): upgrade to docusaurus 2.2.0

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.2.3

chore(dart_frog_cli): v0.2.3

---

examples/todos/routes/todos/[id].dart
examples/todos/routes/todos/index.dart
packages/dart_frog/lib/src/request.dart
packages/dart_frog/lib/src/response.dart
packages/dart_frog/test/src/request_test.dart
packages/dart_frog/test/src/response_test.dart

**READY**
- fix(dart_frog): Request.json() and Response.json() return types (closes #409)
- related to #145

fix(dart_frog): Request.json() and Response.json() return types

---

bricks/create_dart_frog/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/pubspec.yaml

**READY**
- chore(bricks): upgrade to mason 0.1.0-dev.37 (part of #397)

chore(bricks): upgrade to mason 0.1.0-dev.37

---

packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- fix(dart_frog_cli): hook execution after pub cache clean (closes #397)

fix(dart_frog_cli): hook execution after pub cache clean

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.2.4

chore(dart_frog_cli): v0.2.4

---

docs/docs/basics/routes.md

docs(routes): fix typos in code snippets

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.3.0

chore(dart_frog): v0.3.0

---

bricks/create_dart_frog/__brick__/pubspec.yaml
examples/counter/pubspec.yaml
examples/echo/pubspec.yaml
examples/hello_world/pubspec.yaml
examples/kitchen_sink/pubspec.yaml
examples/todos/pubspec.yaml
packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
packages/dart_frog_cli/lib/src/runtime_compatibility.dart
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml
packages/dart_frog_cli/test/src/runtime_compatibility_test.dart

**READY**
- chore(dart_frog_cli): v0.3.0

chore(dart_frog_cli): v0.3.0

---

bricks/create_dart_frog/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/pubspec.yaml

**READY**
- chore(bricks): upgrade to mason ^0.1.0-dev.38

chore(bricks): upgrade to mason ^0.1.0-dev.38

---

docs/docs/basics/dependency-injection.md

**READY**
Just fixing typos as I read the docs 🙂

docs(dependency-injection): fix typo

---

packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- feat(dart_frog_cli): upgrade to mason ^0.1.0-dev.38

feat(dart_frog_cli): upgrade to mason ^0.1.0-dev.38

---

examples/kitchen_sink/e2e/projects_test.dart
examples/kitchen_sink/routes/projects/index.dart
examples/kitchen_sink/test/routes/projects/index_test.dart

**READY**
- test(e2e): add kitchen sink routes and tests for `formData`

test(e2e): add kitchen sink routes and tests for `formData`

---

docs/docs/basics/routes.md

**READY**
- docs(routes): add formData

docs(routes): add formData

---

packages/dart_frog_cli/e2e/test/dart_frog_build_test.dart
packages/dart_frog_cli/lib/src/commands/build/build.dart
packages/dart_frog_cli/test/src/commands/build/build_test.dart

**READY**
- feat(dart_frog_cli): build supports custom Dockerfile (closes #426)

feat(dart_frog_cli): build supports custom Dockerfile

---

docs/docs/advanced/custom_entrypoint.md
docs/docs/advanced/powered_by_header.md
docs/docs/basics/dependency-injection.md
docs/docs/basics/middleware.md
docs/docs/basics/resources.md
docs/docs/basics/routes.md
docs/docs/basics/serving-static-files.md
docs/docs/basics/testing.md
docs/docs/deploy/aws-app-runner.md
docs/docs/deploy/digital-ocean-app-platform.md
docs/docs/deploy/google-cloud-run.md
docs/docs/tutorials/_category_.json
docs/docs/tutorials/counter.md
docs/docs/tutorials/echo.md
docs/docs/tutorials/hello_world.md
docs/docs/tutorials/todos.md

**READY**
- docs: leading emojis in sidebar

docs: leading emojis in sidebar

---

.github/workflows/.docker_tests.yaml
.github/workflows/examples_kitchen_sink.yaml
docs/docs/advanced/custom_dockerfile.md
docs/docs/advanced/powered_by_header.md
docs/docusaurus.config.js
docs/yarn.lock
examples/kitchen_sink/Dockerfile
packages/dart_frog_cli/e2e/test/dart_frog_build_test.dart
packages/dart_frog_cli/lib/src/commands/build/build.dart
packages/dart_frog_cli/test/src/commands/build/build_test.dart

**READY**
- docs(advanced): custom `Dockerfile`

docs(advanced): custom `Dockerfile`

---

docs/docs/advanced/custom_dockerfile.md

**READY**
- docs: move cspell ignore

docs: move cspell ignore

---

.github/workflows/dart_frog_web_socket.yaml
packages/dart_frog_web_socket/.gitignore
packages/dart_frog_web_socket/CHANGELOG.md
packages/dart_frog_web_socket/LICENSE
packages/dart_frog_web_socket/README.md
packages/dart_frog_web_socket/analysis_options.yaml
packages/dart_frog_web_socket/coverage_badge.svg
packages/dart_frog_web_socket/example/README.md
packages/dart_frog_web_socket/lib/dart_frog_web_socket.dart
packages/dart_frog_web_socket/lib/src/web_socket_handler.dart
packages/dart_frog_web_socket/pubspec.yaml
packages/dart_frog_web_socket/test/src/web_socket_handler_test.dart

**HOLD**
- feat(dart_frog_web_socket): add package:dart_frog_web_socket (closes #94)

feat(dart_frog_web_socket): add package:dart_frog_web_socket

---

README.md
docs/docs/advanced/powered_by_header.md
docs/docs/advanced/web_socket.md
docs/docs/overview.md
docs/docs/roadmap.md

docs: WebSockets

---

.github/workflows/examples_web_socket_counter.yaml
README.md
examples/web_socket_counter/.gitignore
examples/web_socket_counter/README.md
examples/web_socket_counter/analysis_options.yaml
examples/web_socket_counter/e2e/ws_test.dart
examples/web_socket_counter/lib/counter/counter.dart
examples/web_socket_counter/lib/counter/cubit/counter_cubit.dart
examples/web_socket_counter/lib/counter/middleware/counter_provider.dart
examples/web_socket_counter/lib/counter/models/message.dart
examples/web_socket_counter/pubspec.yaml
examples/web_socket_counter/pubspec_overrides.yaml
examples/web_socket_counter/routes/_middleware.dart
examples/web_socket_counter/routes/ws.dart
examples/web_socket_counter/test/counter/cubit/counter_cubit_test.dart
examples/web_socket_counter/test/routes/_middleware_test.dart
examples/web_socket_counter/test/routes/ws_test.dart

**READY**
- docs: add web_socket_counter example

docs: add web_socket_counter example

---

docs/docs/tutorials/web_socket_counter.md

**READY**
- docs(web_socket_counter): create tutorial

docs(web_socket_counter): create tutorial

---

packages/dart_frog_gen/test/src/build_route_configuration_test.dart

**READY**
- test(dart_frog_gen): simplify buildRouteConfiguration tests

test(dart_frog_gen): simplify buildRouteConfiguration tests

---

packages/dart_frog_gen/test/src/build_route_configuration_test.dart

**READY**
- test(dart_frog_gen): add tests for multiple variables in route file name

test(dart_frog_gen): add tests for multiple variables in route file name

---

docs/docs/tutorials/web_socket_counter.md

**READY**
docs(web_socket_counter): fix example cURL script in tutorial

docs(web_socket_counter): fix cURL script in tutorial

---

packages/dart_frog_web_socket/pubspec.yaml

**READY**
- fix(dart_frog_web_socket): upgrade to shelf_web_socket ^1.0.3
- closes #463

fix(dart_frog_web_socket): upgrade to shelf_web_socket ^1.0.3

---

packages/dart_frog_web_socket/CHANGELOG.md
packages/dart_frog_web_socket/pubspec.yaml

**READY**
- chore(dart_frog_web_socket): v0.1.0-dev.2

chore(dart_frog_web_socket): v0.1.0-dev.2

---

examples/web_socket_counter/pubspec.yaml

**READY**
- chore(web_socket_counter): upgrade to dart_frog_web_socket ^0.1.0-dev.2

chore(web_socket_counter): upgrade to dart_frog_web_socket ^0.1.0-dev.2

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.3.2

chore(dart_frog): v0.3.2

---

examples/todos/packages/in_memory_todos_data_source/lib/src/in_memory_todos_data_source.dart
examples/todos/packages/todos_data_source/lib/src/models/todo.dart
examples/todos/packages/todos_data_source/lib/src/todos_data_source.dart

**READY**
- chore(examples/todos): fix analyzer warnings in Dart 2.19

chore(examples/todos): fix analyzer warnings in Dart 2.19

---

bricks/create_dart_frog/__brick__/pubspec.yaml
examples/counter/pubspec.yaml
examples/echo/pubspec.yaml
examples/hello_world/pubspec.yaml
examples/kitchen_sink/pubspec.yaml
examples/todos/pubspec.yaml
examples/web_socket_counter/pubspec.yaml

**READY**
- chore: upgrade examples to Dart 2.19

chore: upgrade examples to Dart 2.19

---

packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart

**READY**
- feat(dart_frog_cli): dart_frog create use Dart 2.19

feat(dart_frog_cli): dart_frog create use Dart 2.19

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.3.2

chore(dart_frog_cli): v0.3.2

---

packages/dart_frog_cli/lib/src/command_runner.dart
packages/dart_frog_cli/pubspec.yaml
packages/dart_frog_cli/test/src/command_runner_test.dart
packages/dart_frog_cli/test/src/commands/create/create_test.dart

**READY**
- feat(dart_frog_cli): add cli completion

feat(dart_frog_cli): add cli completion

---

packages/dart_frog_cli/analysis_options.yaml
packages/dart_frog_cli/pubspec.yaml

**READY**
- feat(dart_frog_cli): upgrade to Dart 2.19 and Very Good Analysis 4.0.0

feat(dart_frog_cli): upgrade to Dart 2.19 and Very Good Analysis 4.0.0

---

bricks/create_dart_frog/__brick__/analysis_options.yaml
bricks/create_dart_frog/__brick__/pubspec.yaml
bricks/create_dart_frog/hooks/analysis_options.yaml
bricks/create_dart_frog/hooks/pubspec.yaml

**READY**
- refactor(create_dart_frog): update to Dart 2.19 and Very Good Analysis 4.0.0

refactor(create_dart_frog): update to Dart 2.19 and Very Good Analysis 4.0.0

---

bricks/dart_frog_dev_server/hooks/analysis_options.yaml
bricks/dart_frog_dev_server/hooks/pubspec.yaml

**READY**
- refactor(dart_frog_dev): update to Dart 2.19 and Very Good Analysis 4.0.0

refactor(dart_frog_dev): update to Dart 2.19 and Very Good Analysis 4.0.0

---

docs/docs/basics/resources.md
docs/docs/roadmap.md

docs(resources): minor copy update to fun fact blurb

---

bricks/dart_frog_dev_server/__brick__/server.dart
bricks/dart_frog_prod_server/__brick__/build/bin/server.dart

**READY**
- feat: allow both IPv4 and IPv6 (closes #479)

feat: allow IPv4 and IPv6

---

bricks/dart_frog_dev_server/__brick__/server.dart
bricks/dart_frog_prod_server/__brick__/build/bin/server.dart

**READY**
- fix: adjust `InternetAddress` to `anyIPv6` since HttpServer bind falls back to IPv4 when using `anyIPv6`.
- kudos to @rubenferreira97 (https://github.com/VeryGoodOpenSource/dart_frog/issues/479#issue-1553001741)

fix: adjust InternetAddress to anyIPv6

---

.github/CODEOWNERS
.github/dependabot.yaml

**READY**
chore: update dependabot

chore: update dependabot

---

packages/dart_frog_gen/analysis_options.yaml
packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/pubspec.yaml

**READY**
- refactor(dart_frog_gen): upgrade to Dart 2.19 and Very Good Analysis 4.0.0

refactor(dart_frog_gen): upgrade to Dart 2.19 and Very Good Analysis 4.0.0

---

packages/dart_frog/analysis_options.yaml
packages/dart_frog/lib/dart_frog.dart
packages/dart_frog/lib/src/hot_reload.dart
packages/dart_frog/pubspec.yaml
packages/dart_frog/test/src/router_test.dart
packages/dart_frog/test/src/serve_test.dart

**READY**
- refactor(dart_frog): upgrade to Dart 2.19 and Very Good Analysis 4.0.0

refactor(dart_frog): upgrade to Dart 2.19 and Very Good Analysis 4.0.0

---

packages/dart_frog_web_socket/analysis_options.yaml
packages/dart_frog_web_socket/pubspec.yaml

**READY**
- refactor(dart_frog_web_sockets): upgrade to Dart 2.19 and Very Good Analysis 4.0.0

refactor(dart_frog_web_sockets): upgrade to Dart 2.19 and Very Good Analysis 4.0.0

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
- chore(dart_frog_gen): v0.3.1

chore(dart_frog_gen): v0.3.1

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v0.3.3

chore(dart_frog): v0.3.3

---

packages/dart_frog_web_socket/CHANGELOG.md
packages/dart_frog_web_socket/pubspec.yaml

**READY**
- chore(dart_frog_web_socket): v0.1.0-dev.3

chore(dart_frog_web_socket): v0.1.0-dev.3

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.3.3

chore(dart_frog_cli): v0.3.3

---

docs/docs/basics/resources.md

**READY**
Add link to Awesome Dart Frog repo & remove others (since they're linked elsewhere)

docs(resources): add awesome dart frog

---

docs/docs/overview.md
docs/docs/tutorials/todos.md

**READY**
- docs: update various dependency references

docs: update various dependency references

---

packages/dart_frog_cli/lib/src/commands/dev/dev.dart

**READY**
- refactor(dart_frog_cli): remove duplicate `dart:io` import

refactor(dart_frog_cli): remove duplicate `dart:io` import

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
Releasing v0.3.4 of `dart_frog`

chore(dart_frog): v0.3.4

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
chore(dart_frog): v0.3.5

chore(dart_frog): v0.3.5

---

.github/CODEOWNERS

chore: adding erick as codeowner

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

chore(dart_frog_gen): 0.3.2

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
Release v0.3.4 of `dart_frog_cli`

chore(dart_frog_cli): 0.3.4

---

docs/docs/advanced/custom_dockerfile.md
docs/docs/advanced/custom_init_method.md
docs/docs/advanced/powered_by_header.md
docs/docs/advanced/security_context.md
docs/docs/advanced/web_socket.md

**READY**
Adding docs about the new init method (#564)

docs: add documentation about the init method

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
Release v0.3.5 of `dart_frog_cli`

chore(dart_frog_cli): 0.3.5

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
Release v0.3.6 of `dart_frog`

chore(dart_frog): 0.3.6

---

.gitignore
packages/dart_frog_gen/lib/dart_frog_gen.dart
packages/dart_frog_gen/lib/src/validate_route_configuration/external_path_dependencies.dart
packages/dart_frog_gen/lib/src/validate_route_configuration/rogue_routes.dart
packages/dart_frog_gen/lib/src/validate_route_configuration/route_conflicts.dart
packages/dart_frog_gen/lib/src/validate_route_configuration/validate_route_configuration.dart
packages/dart_frog_gen/pubspec.yaml
packages/dart_frog_gen/test/src/validate_route_configuration/external_path_dependencies_test.dart
packages/dart_frog_gen/test/src/validate_route_configuration/rogue_routes_test.dart
packages/dart_frog_gen/test/src/validate_route_configuration/route_conflicts_test.dart

**READY**
Ref: #611 
Extract some validation made on bricks (with duplicated code) to dart_frog_gen
Lays ground for #260

feat(dart_frog_gen): add route configuration validation to gen

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

chore(dart_frog_gen): 0.3.4

---

bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/pubspec.yaml

**READY**
chore: bump dart_frog_gen version on bricks

chore: bump dart_frog_gen version on bricks

---

bricks/dart_frog_new/__brick__/{{filename}}
bricks/dart_frog_new/__brick__/{{~ middleware.dart }}
bricks/dart_frog_new/__brick__/{{~ route.dart }}
bricks/dart_frog_new/hooks/lib/post_gen.dart
bricks/dart_frog_new/hooks/lib/pre_gen.dart
bricks/dart_frog_new/hooks/test/post_gen_test.dart
bricks/dart_frog_new/hooks/test/pre_gen_test.dart

**READY**
Continuation of  #623
ref: #260

feat(dart_frog_cli): add dart_frog_new_brick (middleware implementation)

---

tool/generate_bundles.sh

**READY**
chore: point bundle generation to the main branch

chore: point bundle generation to the main branch

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/README.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
chore(dart_frog_cli): v0.3.6

chore(dart_frog_cli): v0.3.6

---

README.md
docs/docs/basics/middleware.md
docs/docs/basics/routes.md
docs/docs/roadmap.md

**READY**
docs: add `new` command reference

docs: add `new` command reference

---

bricks/dart_frog_prod_server/hooks/test/post_gen_test.dart
bricks/dart_frog_prod_server/hooks/test/src/dart_pub_get_test.dart
packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/test/src/commands/dev/dev_test.dart
packages/dart_frog_cli/test/src/commands/update/update_test.dart

**READY**
This will be problematic when on dart 3, just preparing :D

refactor(dart_frog_cli): do not mock process result

---

bricks/dart_frog_prod_server/__brick__/build/Dockerfile
bricks/dart_frog_prod_server/brick.yaml
bricks/dart_frog_prod_server/hooks/pre_gen.dart
bricks/dart_frog_prod_server/hooks/test/pre_gen_test.dart

**READY**
This is a first step to support a new flag on the build command for a custom dart version.
Related to #603

feat: adding option to customize the dart version on the build brick

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
chore(dart_frog_cli): v0.3.7

chore(dart_frog_cli): v0.3.7

---

packages/dart_frog_cli/.gitignore

**READY**
chore: do not ingnore build

chore: do not ingnore build

---

bricks/create_dart_frog/__brick__/analysis_options.yaml
bricks/create_dart_frog/__brick__/pubspec.yaml
bricks/create_dart_frog/hooks/analysis_options.yaml
bricks/create_dart_frog/hooks/pubspec.yaml

**READY**
refactor(create_dart_frog): update to Dart 3 and Very Good Analysis 5

refactor(create_dart_frog): update to Dart 3 and Very Good Analysis 5

---

docs/docs/basics/environments.md

**READY**
Remove line under H1

docs: Update environments.md

---

packages/dart_frog/analysis_options.yaml
packages/dart_frog/lib/src/request_logger.dart
packages/dart_frog/pubspec.yaml

**READY**
refactor(dart_frog): update to Dart 3 and Very Good Analysis 5

refactor(dart_frog): update to Dart 3 and Very Good Analysis 5

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
chore(dart_frog): 0.3.7

chore(dart_frog): v0.3.7

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
chore(dart_frog_cli): v0.3.8

chore(dart_frog_cli): v0.3.8

---

.github/workflows/dart_frog_vscode.yaml

**READY**
Fixes a small workflow typo introduced when applying a code suggestion.

ci(vscode): fix workflow typo

---

packages/dart_frog_cli/lib/src/command_runner.dart
packages/dart_frog_cli/lib/src/commands/commands.dart
packages/dart_frog_cli/lib/src/commands/daemon/daemon.dart
packages/dart_frog_cli/lib/src/daemon/daemon.dart
packages/dart_frog_cli/test/src/commands/daemon/daemon_test.dart
packages/dart_frog_cli/test/src/daemon/daemon_test.dart

**READY**
feat: add `dart_frog daemon` command
Adding this command with basic placeholder behavior. 
The first step into #705

feat(dart_frog_cli): add `dart_frog daemon` command

---

packages/dart_frog/lib/src/context.dart
packages/dart_frog/lib/src/provider.dart
packages/dart_frog/test/src/provider_test.dart

**READY**
- feat(dart_frog): provider support nullable values (closes #688)

feat(dart_frog): provider support nullable values

---

extensions/vscode/package-lock.json
extensions/vscode/package.json
extensions/vscode/src/test/suite/utils/cli-version.test.ts
extensions/vscode/src/utils/cli-version.ts
extensions/vscode/src/utils/utils.ts

**READY**
Adds functions to ensure the CLI version installed is compatible with the extension.

feat(vscode): add CLI version compatibility functions

---

.github/dependabot.yaml

**READY**
Adds npm dependabot for the Visual Studio Code extension.

ci(vscode): add dependabot

---

extensions/vscode/README.md
extensions/vscode/package.json
extensions/vscode/src/commands/index.ts
extensions/vscode/src/commands/install-cli.ts
extensions/vscode/src/commands/update-cli.ts
extensions/vscode/src/extension.ts
extensions/vscode/src/test/suite/commands/update-cli.test.ts
extensions/vscode/src/test/suite/extension.test.ts
extensions/vscode/src/utils/cli-version.ts

**READY**
Adds a simple command to update the Dart Frog CLI.
The idea behind this PR is to, whenever an old and non-compatible version of Dart Frog CLI is detected to proceed and update the CLI. There would be an upcoming Pull Request (#752) that will add said functionality.
Note, this Pull Request is a partial follow-up to the comment [here](https://github.com/VeryGoodOpenSource/dart_frog/pull/726#discussion_r1242069556).

feat(vscode): add update-cli command

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
chore(dart_frog): v0.3.8

chore(dart_frog): v0.3.8

---

packages/dart_frog_cli/lib/src/commands/new/templates/dart_frog_new_bundle.dart

**READY**
Brings #790 to the cli
Fixes https://github.com/VeryGoodOpenSource/dart_frog/issues/746

fix(dart_frog_cli): Remove multiple EOL when creating route or middleware

---

.github/cspell.json
packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
chore(dart_frog_cli): v0.3.9

chore(dart_frog_cli): v0.3.9

---

packages/dart_frog_auth/CHANGELOG.md
packages/dart_frog_auth/pubspec.yaml
packages/dart_frog_auth/test/src/dart_frog_auth_test.dart

**READY**
chore(dart_frog_auth): v0.1.0

chore(dart_frog_auth): v0.1.0

---

packages/dart_frog_cli/e2e/test/dev_test.dart
packages/dart_frog_cli/e2e/test/helpers/dart_analyze.dart
packages/dart_frog_cli/e2e/test/helpers/dart_format.dart
packages/dart_frog_cli/e2e/test/helpers/dart_frog_build.dart
packages/dart_frog_cli/e2e/test/helpers/dart_frog_create.dart
packages/dart_frog_cli/e2e/test/helpers/dart_frog_daemon.dart
packages/dart_frog_cli/e2e/test/helpers/dart_frog_new.dart
packages/dart_frog_cli/e2e/test/helpers/dart_tst.dart
packages/dart_frog_cli/e2e/test/helpers/helpers.dart
packages/dart_frog_cli/e2e/test/helpers/kill_dart_frog_server.dart
packages/dart_frog_cli/e2e/test/helpers/run_process.dart
packages/dart_frog_cli/e2e/test/new_test.dart

**READY**
test(dart_frog_cli_e2e): improve process run output and fix intermittency

test(dart_frog_cli_e2e): improve process run output and fix intermittency

---

packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/lib/src/daemon/daemon_server.dart
packages/dart_frog_cli/lib/src/daemon/domain/daemon_domain.dart
packages/dart_frog_cli/lib/src/daemon/domain/dev_server_domain.dart
packages/dart_frog_cli/lib/src/daemon/domain/domain.dart
packages/dart_frog_cli/lib/src/daemon/domain/domain_base.dart
packages/dart_frog_cli/lib/src/dev_server_runner/dev_server_runner.dart
packages/dart_frog_cli/pubspec.yaml
packages/dart_frog_cli/test/src/daemon/daemon_server_test.dart
packages/dart_frog_cli/test/src/daemon/domain/daemon_domain_test.dart
packages/dart_frog_cli/test/src/daemon/domain/dev_server_domain_test.dart
packages/dart_frog_cli/test/src/daemon/domain/domain_base_test.dart

**READY**
#705 
Comes after #801

feat: add devserver domain to daemon

---

packages/dart_frog_cli/e2e/test/daemon/daemon_domain_test.dart
packages/dart_frog_cli/e2e/test/daemon/dev_server_domain_test.dart
packages/dart_frog_cli/e2e/test/helpers/dart_frog_daemon.dart
packages/dart_frog_cli/e2e/test/helpers/kill_dart_frog_server.dart
packages/dart_frog_cli/e2e/test/helpers/test_server.dart

**READY**
test(dart_frog_cli_e2e): add e2e tests for devserver domain

test(dart_frog_cli_e2e): add e2e tests for devserver domain

---

extensions/vscode/src/test/suite/utils/cli-version.test.ts
extensions/vscode/src/utils/cli-version.ts

**READY**
Fix dart frog version parsing in vscode extensión when an update is available

fix(vscode): dart frog version parsing when update available

---

docs/docs/basics/routes.md

update admonition
**READY**
update admonition

docs: update routes.md

---

packages/dart_frog_cli/lib/src/commands/update/update.dart
packages/dart_frog_cli/test/src/commands/update/update_test.dart

**READY**
Added new --verify-only flag to update command
Fixes #707

feat: add verify-only flag to update command

---

extensions/vscode/CONTRIBUTING.md

**READY**
Resolved https://github.com/VeryGoodOpenSource/dart_frog/issues/753.

docs(vscode): include information regarding random test ordering

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
chore(dart_frog_gen): v1.0.0

chore(dart_frog_gen): v1.0.0

---

.github/workflows/publish.yaml

**READY**
ci: diable publish workflow
temporary for #789

ci: disable publish workflow

---

bricks/create_dart_frog/__brick__/pubspec.yaml
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/test/pre_gen_test.dart
bricks/dart_frog_new/hooks/pubspec.yaml
bricks/dart_frog_new/hooks/test/pre_gen_test.dart
bricks/dart_frog_new/hooks/test/src/route_configuration_utils_test.dart
bricks/dart_frog_prod_server/hooks/pubspec.yaml

**READY**
chore: bump dart_frog_gen

feat: bump dart_frog_gen on bricks

---

extensions/vscode/CHANGELOG.md
extensions/vscode/package-lock.json
extensions/vscode/package.json
extensions/vscode/src/test/suite/utils/cli-version.test.ts
extensions/vscode/src/utils/cli-version.ts

**READY**
Release 0.1.0 of the VS Code extension.
Changes:
- Downgraded types to be publishable
- Upgraded version constraints to be compatible with upcoming CLI version
- Included CHANGELOG.md to report the first release

chore(vscode): v0.1.0

---

docs/docs/advanced/authentication.md

**READY**
Fix unlinked General Http text.

docs(authentication): fix link to general http

---

docs/docs/advanced/authentication.md

**READY**
- docs(authentication): fix typo

docs(authentication): fix typo

---

extensions/vscode/README.md

**READY**
Update **README.md** with new links.
Changes:
- Remove dark logo
- Updates VS Code link
- Updated demo link

docs(vscode): update README links and style

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
chore(dart_frog): v1.0.0

chore(dart_frog): v1.0.0

---

packages/dart_frog_auth/CHANGELOG.md
packages/dart_frog_auth/pubspec.yaml

**READY**
chore(dart_frog_auth): v1.0.0

chore(dart_frog_auth): v1.0.0

---

packages/dart_frog_web_socket/CHANGELOG.md
packages/dart_frog_web_socket/pubspec.yaml

**READY**
chore(dart_frog_web_socket): v1.0.0

chore(dart_frog_web_socket): v1.0.0

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/e2e/test/new_test.dart
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
chore(dart_frog_cli): v1.0.0

chore(dart_frog_cli): v1.0.0

---

docs/docs/advanced/cors.md

**READY**
Adds a brief documentation about handling CORS in a Dart Frog server.
ref: https://github.com/VeryGoodOpenSource/dart_frog/issues/524

docs: Adding docs about CORS

---

docs/docs/advanced/cors.md

**READY**
Update admonition to note instead of warning

docs: update cors.md

---

packages/dart_frog_cli/lib/src/commands/daemon/daemon.dart
packages/dart_frog_cli/test/src/command_runner_test.dart

**READY**
feat(dart_frig_cli): make daemon command visible

feat(dart_frig_cli): make daemon command visible

---

bricks/dart_frog_dev_server/__brick__/server.dart
bricks/dart_frog_prod_server/__brick__/build/bin/server.dart

**READY**
If a `PORT` variable has an invalid integer, server will fail to start

fix: port read from env

---

.github/workflows/update_cli_bundles.yaml

**READY**
ci: add update_cli_bundles
This ensures the bundles are up to date

ci: add update_cli_bundles

---

docs/docs/overview.md
docs/docs/tutorials/todos.md

**READY**
update versions on docs

docs: update versions on docs

---

docs/docs/advanced/authentication.md

docs: add link to authentication.md

---

.github/dependabot.yaml

**READY**
JS people, from at least one of the 10 Billion dependencies we have, release patches almost every day, and it is hard to keep up with the dependabot PRs. 
This PR changes the interval to weekly.

chore: change dependabot updates

---

extensions/vscode/package.json
extensions/vscode/src/extension.ts
extensions/vscode/src/test/suite/extension.test.ts

**READY**
Renamed the commands prefix to be "dart-frog" instead of "extension".

refactor(vscode): rename command prefix to "dart-frog"

---

packages/dart_frog_gen/CHANGELOG.md
packages/dart_frog_gen/pubspec.yaml

**READY**
chore(dart_frog_gen): v1.1.0

chore(dart_frog_gen): v1.1.0

---

extensions/vscode/src/daemon/dart-frog-daemon.ts
extensions/vscode/src/test/suite/daemon/dart-frog-daemon.test.ts

**READY**
Allows invoking the Dart Frog daemon.
Changes:
- Defined `invoke` method to start the daemon
- Define `on` and `off` methods to subscribe to daemon events

feat(vscode): allow invoking Dart Frog daemon

---

bricks/dart_frog_dev_server/hooks/pre_gen.dart
bricks/dart_frog_dev_server/hooks/test/pre_gen_test.dart

**READY**
Removed checking about external dependencies in the dev brick.

feat: removing external dependencies checking from dev brick

---

bricks/create_dart_frog/__brick__/.gitignore

**READY**
Adds the `.DS_Store` file to the `create_dart_frog` brick .gitignore
Resolving Issue #909

chore: add .DS_Store to create_dart_frog gitignore

---

packages/dart_frog/test/src/body_parsers/form_data_test.dart
packages/dart_frog/test/src/request_test.dart
packages/dart_frog/test/src/response_test.dart

**READY**
Runs `dart fix --apply` in packages/dart_frog.
- New analyser changed the trailing comma lint rule
- Blocking https://github.com/VeryGoodOpenSource/dart_frog/pull/939

fix(dart_frog): comply with new analysis rules

---

packages/dart_frog_auth/CHANGELOG.md
packages/dart_frog_auth/pubspec.yaml

chore(dart_frog_auth): 1.1.0

---

packages/dart_frog_auth/pubspec.yaml

**READY**
Pub dev only allow 5 topics

fix: auth topics

---

extensions/vscode/src/commands/stop-dev-server.ts
extensions/vscode/src/test/suite/commands/stop-dev-server.test.ts
extensions/vscode/src/test/suite/utils/dart-frog-application.test.ts
extensions/vscode/src/utils/dart-frog-application.ts
extensions/vscode/src/utils/index.ts

**READY**
Refactors quickPickApplication function and moves it to utils to be shared by #955 .
Changes:
- Moves quickPickApplication to utils
- Allows passing options to configure quickPickApplication
- quickPickApplication is not busy by default

refactor(vscode): allow quickPickApplication to be shared

---

README.md
packages/dart_frog/README.md
packages/dart_frog_auth/README.md
packages/dart_frog_cli/README.md
packages/dart_frog_web_socket/README.md

**READY**
docs: add links to docs on readmes
Raised by #976

docs: add links to docs on readmes

---

examples/basic_authentication/analysis_options.yaml
examples/basic_authentication/pubspec.yaml
examples/bearer_authentication/analysis_options.yaml
examples/bearer_authentication/pubspec.yaml
examples/counter/analysis_options.yaml
examples/counter/pubspec.yaml
examples/echo/analysis_options.yaml
examples/echo/pubspec.yaml
examples/hello_world/analysis_options.yaml
examples/hello_world/pubspec.yaml
examples/kitchen_sink/analysis_options.yaml
examples/kitchen_sink/pubspec.yaml
examples/todos/analysis_options.yaml
examples/todos/packages/in_memory_todos_data_source/analysis_options.yaml
examples/todos/packages/in_memory_todos_data_source/pubspec.yaml
examples/todos/packages/todos_data_source/analysis_options.yaml
examples/todos/packages/todos_data_source/pubspec.yaml
examples/todos/pubspec.yaml
examples/web_socket_counter/analysis_options.yaml
examples/web_socket_counter/pubspec.yaml

**READY**
chore(examples): bump very good analysis and dart constraint

chore(examples): bump very good analysis and dart constraint

---

packages/dart_frog_cli/e2e/test/dev_test.dart

ci: false negatives on tests

---

bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_new/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/pubspec.yaml
packages/dart_frog_cli/pubspec.yaml

**READY**
chore: update dart_frog_gen on bricks

chore: update dart_frog_gen on bricks

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
chore(dart_frog): 1.0.1

chore(dart_frog): v1.0.1

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
chore(dart_frog_cli): v1.1.0

chore(dart_frog_cli): 1.1.0

---

docs/docs/advanced/daemon.md

**READY**
docs: add docs for route config domain

docs: add docs for route config domain

---

bricks/create_dart_frog/__brick__/.vscode/extensions.json
examples/basic_authentication/.vscode/extensions.json
examples/bearer_authentication/.vscode/extensions.json
examples/counter/.vscode/extensions.json
examples/echo/.vscode/extensions.json
examples/hello_world/.vscode/extensions.json
examples/kitchen_sink/.vscode/extensions.json
examples/todos/.vscode/extensions.json
examples/web_socket_counter/.vscode/extensions.json

**READY**
feat: add dart frog extension as recommended

feat: add dart frog extension as recommended

---

extensions/vscode/src/daemon/dart-frog-application.ts
extensions/vscode/src/status-bar/open-application-status-bar-item.ts
extensions/vscode/src/test/suite/daemon/dart-frog-application.test.ts
extensions/vscode/src/utils/dart-frog-application.ts

**READY**
Part of #912.
Changes:
- Includes a host member in the DartFrogApplication class.

feat(vscode): include host member in DartFrogApplication

---

packages/dart_frog_cli/e2e/test/daemon/route_configuration_domain_test.dart
packages/dart_frog_cli/e2e/test/helpers/dart_frog_daemon.dart

**READY**
test: investigate intermitent test

test: fix intermitent e2e test

---

extensions/vscode/src/code-lens/on-request-code-lens.ts
extensions/vscode/src/commands/new-middleware.ts
extensions/vscode/src/commands/new-route.ts
extensions/vscode/src/commands/start-daemon.ts
extensions/vscode/src/commands/start-dev-server.ts
extensions/vscode/src/test/suite/code-lens/on-request-code-lens.test.ts
extensions/vscode/src/test/suite/commands/new-middleware.test.ts
extensions/vscode/src/test/suite/commands/new-route.test.ts
extensions/vscode/src/test/suite/commands/start-daemon.test.ts
extensions/vscode/src/test/suite/commands/start-dev-server.test.ts
extensions/vscode/src/test/suite/commands/stop-dev-server.test.ts
extensions/vscode/src/test/suite/utils/dart-frog-structure.test.ts
extensions/vscode/src/utils/dart-frog-structure.ts

**READY**
Renames `nearestDartFrogProject` to `nearestParentDartFrogProject` in preparation to support monorepos, see #1011 .
Changes:
- Renames `nearestDartFrogProject` to `nearestParentDartFrogProject`

refactor(vscode): rename nearestDartFrogProject to nearestParentDartFrogProject

---

extensions/vscode/src/test/suite/commands/start-dev-server.test.ts

**READY**
Simplify `start-dev-server.test.ts` to reuse stubs and default returns.

test(vscode): simplify start-dev-server tests

---

extensions/vscode/package.json

**READY**
Rollbacks to VS Code engine to 1.79.0, since the engine version was updated unnecessarily by DependaBot, see #1033.

chore(vscode): rollback engines.vscode version

---

extensions/vscode/CHANGELOG.md
extensions/vscode/package-lock.json
extensions/vscode/package.json

**READY**
See the CHANGELOG for more information.

chore(vscode): 0.2.1

---

packages/dart_frog_cli/e2e/test/daemon/dev_server_domain_test.dart
packages/dart_frog_cli/e2e/test/daemon/route_configuration_domain_test.dart
packages/dart_frog_cli/e2e/test/helpers/dart_frog_daemon.dart
packages/dart_frog_cli/lib/src/daemon/domain/dev_server_domain.dart
packages/dart_frog_cli/lib/src/daemon/domain/route_configuration_domain.dart
packages/dart_frog_cli/test/src/daemon/domain/dev_server_domain_test.dart
packages/dart_frog_cli/test/src/daemon/domain/route_configuration_domain_test.dart

**READY**
fix(dart_frog_cli): prevent staggered devserver kills

fix(dart_frog_cli): prevent staggered devserver kills

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
chore(dart_frog_cli): v1.1.1

chore(dart_frog_cli): v1.1.1

---

extensions/vscode/README.md

**READY**
Changes:
- Adds a disclaimer to encourage the community to submit issues or ideas

docs(vscode): add disclaimer to the extension

---

docs/docs/advanced/daemon.md

**READY**
Fix #1013 
- Add methods usage examples
- Add early stage warning
- Add end to end implementation reference

docs(dart_frog_cli): Add methods usage examples

---

extensions/vscode/src/utils/dart-frog-project.ts

fix(vscode): ensure nearestParentDartFrogProject is Windows compatible

---

extensions/vscode/src/commands/create.ts
extensions/vscode/src/test/suite/commands/create.test.ts

**READY**
Uses double quotes over single quote to ensure create command is Windows compatible.

fix(vscode): ensure create command is Windows compatible

---

extensions/vscode/src/test/suite/commands/create.test.ts

**READY**
Used double quotes on create for those instances that were not updated on https://github.com/VeryGoodOpenSource/dart_frog/pull/1068

test(vscode): used double quotes on create stub

---

extensions/vscode/CHANGELOG.md
extensions/vscode/package-lock.json
extensions/vscode/package.json

**READY**
See CHANGELOG for more information.

chore(vscode): 0.2.3

---

packages/dart_frog/lib/src/request.dart

**READY**
Solves "dart(doc_directive_missing_closing_tag)" analysis issue.

docs: fix bad "request" template

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/dev_server_runner/dev_server_runner.dart
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
chore(dart_frog_cli): 1.2.0
- [c] 🗑️ Chore

chore(dart_frog_cli): 1.2.0

---

docs/docs/advanced/daemon.md
docs/docs/overview.md

**READY**
docs: add hostname docs

docs: add hostname docs

---

.github/workflows/deploy.yaml

**READY**
This got missed in #1182. Need to update the node version in the deploy workflow

ci: update node version for doc deploy

---

docs/docs/tutorials/todos.md

removed error by typecasting
**READY/IN DEVELOPMENT/HOLD**

docs: add missing typecasting to the todos tutorial

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
Changes in `CHANGELOG.md`.

chore(dart_frog_cli): 1.2.1

---

bricks/dart_frog_prod_server/hooks/lib/src/create_external_packages_folder.dart
bricks/dart_frog_prod_server/hooks/lib/src/get_internal_path_dependencies.dart
bricks/dart_frog_prod_server/hooks/lib/src/get_pubspec_lock.dart
bricks/dart_frog_prod_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/test/pubspec_locks.dart

**READY**
Resolves #1124 
Changes:
- Removes `pubspec_lock` dependency and its usage.
- Adds an overridden dependency to ensure use cases such as #1124 are solved

refactor(dart_frog_prod_server): remove pubspec lock dependency

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
Related to #1274 
See changes in the CHANGELOG.

chore(dart_frog_cli): 1.2.2

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
Changes available in the CHANGELOG.
Related to #1274

chore(dart_frog): 1.1.0

---

.github/labels.yml
.github/workflows/sync_labels.yaml

**READY**
Add label sync. Also adding a separate file for adding in the Dart Frog specific tags for the different products we have in the repo

chore: add label sync

---

.github/workflows/sync_labels.yaml

**READY**
Need to actually pickup the local `labels.yml` file as well in the Sync Labels action.

chore: actually use local label file

---

packages/dart_frog_auth/lib/src/dart_frog_auth.dart

refactor: added argument name to the Applies typedef

---

packages/dart_frog_cli/lib/src/commands/new/new.dart
packages/dart_frog_cli/test/src/commands/new/new_test.dart

fix: allow `$` in new commands

---

docs/docs/basics/testing.md

**READY**
Small fix in Testing documentation page.

docs: fix testing.md `context.read` typo

---

bricks/create_dart_frog/__brick__/pubspec.yaml

chore: update create_dart_frog brick pubspec.yaml

---

docs/docs/deploy/globe.md

READY
Add a docs section about the new Globe templates area for Dart Frog:

docs(deploy): Add section on Globe templates

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
Changes in CHANGELOG.

chore(dart_frog_cli): 1.2.3

---

docs/docs/basics/environments.md

**READY**
The suggested command `dart_frog serve` does not exists in the current tooling (see the "help" output below), I think it should be `dart_frog dev` instead.
```txt
Available commands:
build       Create a production build.
create      Creates a new Dart Frog app.
daemon      Start the Dart Frog daemon
dev         Run a local development server.
list        Lists the routes on a Dart Frog project.
new         Create a new route or middleware for dart_frog
uninstall   Explains how to uninstall the Dart Frog CLI.
update      Update the Dart Frog CLI.
```

docs: update environment documentation to use dart_frog dev

---

extensions/vscode/CHANGELOG.md
extensions/vscode/package-lock.json
extensions/vscode/package.json

**READY**
Maintenance release for VSCode extension

chore(vscode): 0.2.5

---

.github/workflows/dart_frog_vscode.yaml
.github/workflows/publish_extension_vscode.yaml

**READY**
Updating workflows to move to Node 22 LTS for VS Code Extension. Part of #1575

feat: update node version for VS Code Extension

---

extensions/vscode/CHANGELOG.md
extensions/vscode/package-lock.json
extensions/vscode/package.json

**READY**
Maintenance release for VS Code extension

chore(vscode): 0.2.6

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
Ready release of CLI for 1.2.5 with fix for pub publishing

chore(dart_frog_cli): 1.2.5

---

docs/docs/overview.md
packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/lib/src/dev_server_runner/dev_server_runner.dart
packages/dart_frog_cli/test/src/commands/dev/dev_test.dart

**READY**
Allow developers to pass any dart parameter over the `dart_frog dev` command

feat(dart_frog_cli): allow pass through of arguments

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v1.2.1

chore(dart_frog): v1.2.1

---

docs/astro.config.mjs
docs/src/content/docs/blog/future-of-dart-frog.mdx
docs/src/content/docs/index.mdx
docs/src/styles/landing.css

**READY**
- docs: minor landing page improvements

docs: minor landing page improvements

---

docs/src/content/docs/basics/dependency-injection.mdx
docs/src/content/docs/basics/environment.mdx
docs/src/content/docs/blog/future-of-dart-frog.mdx

**READY**
- docs: minor fixes to copy and snippets

docs: minor fixes to copy and snippets

---

README.md
packages/dart_frog/README.md
packages/dart_frog_auth/README.md
packages/dart_frog_cli/README.md
packages/dart_frog_gen/README.md
packages/dart_frog_test/README.md
packages/dart_frog_web_socket/README.md

**READY**
- docs: add discord badge

docs: add discord badge

---

packages/dart_frog_test/CHANGELOG.md
packages/dart_frog_test/pubspec.yaml

**READY**
- chore(dart_frog_test): v0.1.1

chore(dart_frog_test): v0.1.1

---

.github/workflows/update_cli_bundles.yaml

**READY**
- chore: minor fix to update_cli_bundles

chore: minor fix to update_cli_bundles

---

README.md

**READY**
- docs: add `dart_frog_test` to `README`

docs: add `dart_frog_test` to `README`

---

.github/workflows/update_cli_bundles.yaml
bricks/create_dart_frog/brick.yaml
bricks/dart_frog_dev_server/brick.yaml
bricks/dart_frog_new/brick.yaml
bricks/dart_frog_prod_server/brick.yaml

**READY**
- chore(bricks): bump mason version

chore(bricks): bump mason version

---

extensions/vscode/CONTRIBUTING.md

**READY**
- Add the missing documentation about the release process found in Notion (VGV).

docs(vscode): add release docs

---

packages/dart_frog_auth/pubspec_overrides.yaml
packages/dart_frog_cli/pubspec_overrides.yaml
packages/dart_frog_test/pubspec_overrides.yaml
packages/dart_frog_web_socket/pubspec_overrides.yaml

**READY**
- chore: add `pubspec_overrides.yaml`

chore: add `pubspec_overrides.yaml`

---

.github/dependabot.yaml

**READY/D**
Update dependabot to include pub packages

chore: fix dependabot file

---

packages/dart_frog_test/example/analysis_options.yaml
packages/dart_frog_test/example/pubspec.yaml

**READY**
- chore: adjust dart_frog_test/example to use dart_frog_lint

chore: adjust dart_frog_test/example to use dart_frog_lint

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): v1.2.3

chore(dart_frog): v1.2.3

---

packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): upgrade minimum dart sdk constraint (related to #1831)
- bumping to 3.5.4 to be consistent with `pkg:mason`

chore(dart_frog_cli): upgrade minimum dart sdk constraint

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v1.2.7

chore(dart_frog_cli): v1.2.7

---

packages/dart_frog/pubspec.yaml

**READY**
- chore(dart_frog): minor `pubspec.yaml` adjustments

chore(dart_frog): minor `pubspec.yaml` adjustments

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v1.2.10

chore(dart_frog_cli): v1.2.10
