packages/dart_frog/lib/src/response.dart

READY
Hello @felangel !
Thanks for this package, I've been waiting a long time for a convenient backend framework for dart.
I think that the body field of Response.json should be typed [Object?]
As an example, my legacy project uses a List response like in [jsonplaceholder example](https://jsonplaceholder.typicode.com/users)
Maybe only Map<String, dynamic>? has some hidden meaning that I didn't know?

feat: change `Response.json` body to type `Object?`

---

docs/docusaurus.config.js

**READY**
In the footer of the docs site:
- Remove the roadmap link in the "docs" section
- Point the roadmap link in the "resources" section to the correct page

docs: replace duplicate roadmap link in footer

---

examples/todos/test/routes/todos/[id]_test.dart

**This commit resolves** #310 
**READY**
The test description for the `examples/todos` app inside the `test/routes/todos/[id]_test.dart` should be
```dart
test('responds with a 204 and deletes the todo', () async { 
```
instead of
```dart
test('responds with a 202 and deletes the todo', () async { 
```
as `HttpStatus.noContent` represents the `statusCode` of 204.
https://github.com/VeryGoodOpenSource/dart_frog/blob/5dd17bd3076dabd05fff036a59f5f9f295605621/examples/todos/test/routes/todos/%5Bid%5D_test.dart#L131-L132

test(examples/todos): update test description to use correct status code

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY**
- chore(dart_frog_cli): v0.3.1

chore(dart_frog_cli): v0.3.1

---

packages/dart_frog_cli/lib/src/commands/update/update.dart
packages/dart_frog_cli/pubspec.yaml
packages/dart_frog_cli/test/src/commands/update/update_test.dart

**READY**
fix: update silently fails when the SDK doesn't support the most recent version fo the cli
depends on a new version of the pub updater: https://github.com/VeryGoodOpenSource/pub_updater/pull/37

fix(mason_cli): update silently fails when the sdk is incompatible

---

docs/docs/advanced/custom_init_method.md

READY
It was missing a `/` in URLs

fix: url in "custom_init_method" doc

---

examples/counter/test/routes/_middleware_test.dart
examples/kitchen_sink/test/routes/_middleware_test.dart
examples/web_socket_counter/test/routes/_middleware_test.dart
packages/dart_frog/lib/src/pipeline.dart
packages/dart_frog/test/src/middleware_test.dart
packages/dart_frog/test/src/provider_test.dart

**READY**
Currently, when using Dart Frog in a situation where middleware is applied, the `RequestContext` which the `Handler` is called with is not the same `RequestContext` which the `Middleware` is called with. This is problematic especially in tests because it is not possible to mock dependencies which are accessed via `context.read` from within middleware.
See the following example:
```dart
Future<Response> onRequest(RequestContext context, String id) async {
Future<Response> handler(RequestContext context) async {
final user = context.read<User>();
return Response();
}
return handler.use(middleware)(context);
}
Middleware middleware(String id) {
return (handler) {
return (context) async {
final database = context.read<Database>();
final user = await database.getUserById(id);
return …
```

fix(dart_frog): `Pipeline` does not maintain `RequestContext`

---

.gitignore
packages/dart_frog/lib/src/response.dart
packages/dart_frog/test/src/response_test.dart

**READY**
Fixes the bug that didn't allow overriding content-type headers when using `Response.json()` constructor
Closes #593

fix(dart_frog): `Response.json()` overwrites `content-type` header

---

.gitignore
packages/dart_frog_gen/lib/dart_frog_gen.dart
packages/dart_frog_gen/lib/src/validate_route_configuration/external_path_dependencies.dart
packages/dart_frog_gen/lib/src/validate_route_configuration/rogue_routes.dart
packages/dart_frog_gen/lib/src/validate_route_configuration/route_conflicts.dart
packages/dart_frog_gen/lib/src/validate_route_configuration/validate_route_configuration.dart
packages/dart_frog_gen/pubspec.yaml
packages/dart_frog_gen/test/src/validate_route_configuration/external_path_dependencies_test.dart
packages/dart_frog_gen/test/src/validate_route_configuration/rogue_routes_test.dart
packages/dart_frog_gen/test/src/validate_route_configuration/route_conflicts_test.dart

**READY**
Re-land #614
Braking change: this will break the "server" bricks (see what happened to people on #626)

feat(dart_frog_gen)!: reland "add route configuration validation to gen"

---

packages/dart_frog_cli/.gitignore
packages/dart_frog_cli/README.md
packages/dart_frog_cli/lib/src/command_runner.dart
packages/dart_frog_cli/lib/src/commands/commands.dart
packages/dart_frog_cli/lib/src/commands/list/list.dart
packages/dart_frog_cli/pubspec.yaml
packages/dart_frog_cli/test/src/command_runner_test.dart
packages/dart_frog_cli/test/src/commands/list/list_test.dart

**READY**
Adds a new list command to Dart frog, which will run the dart gen logic in order to gather all the endpoints available in the project, and print them in the console, making it easier for users get a summary of all the available endpoints in their project, without have to open the sourcebase in a file explorer.
This command can be improved in the future to show the HTTP method when we have a way of identifying them.

feat: adding list command

---

packages/dart_frog_gen/lib/src/build_route_configuration.dart
packages/dart_frog_gen/test/src/build_route_configuration_test.dart
packages/dart_frog_gen/test/src/route_directory_test.dart
packages/dart_frog_gen/test/src/route_file_test.dart
packages/dart_frog_gen/test/src/validate_route_configuration/rogue_routes_test.dart
packages/dart_frog_gen/test/src/validate_route_configuration/route_conflicts_test.dart

**READY**
Implemente wildcard route detection at dart_frog_gen. Will unblock #676

feat: adding wildcard detection to dart frog gen

---

packages/dart_frog_gen/lib/src/validate_route_configuration/route_conflicts.dart
packages/dart_frog_gen/pubspec.yaml
packages/dart_frog_gen/test/src/build_route_configuration_test.dart
packages/dart_frog_gen/test/src/validate_route_configuration/route_conflicts_test.dart

**READY**
This PR adds a validation to detect dynamic routes that would eventually "override" non dynamic ones and adds an error to notify the user, so that route issue don't go unnoticeable.
Ideally, we would try to order the routes in a way that the non dynamics ones would take precedence over the dynamic, but that proved a complicated implementation which would bring many other complications related to middlewares.
Since the user can still simply use a single dynamic route to both handle a `GET /pets/123` and a `GET /pets/mine`, we decided to go with marking routes as conflicted when we encounter such cases.
Example output:
Fixes #658
Fixes: #631

feat: detect conflict between dynamic routes and non dynamic ones

---

docs/docs/basics/routes.md

Fixed the code-block/body-content formatting in the Wildcard section of the `routes.md` file.
READY
There were some extra/missing backticks in the **Wildcard** and **Route conflicts** sections that was causing body content to be code-formatted and sample code to be body-formatted.
Also fixed a small typo in the wildcard example ("stared" --> "starred").

docs: fix code blocks and styling in routes.md

---

.github/workflows/examples_bearer_authentication.yaml
examples/bearer_authentication/.gitignore
examples/bearer_authentication/README.md
examples/bearer_authentication/analysis_options.yaml
examples/bearer_authentication/lib/hash_extension.dart
examples/bearer_authentication/lib/session_repository.dart
examples/bearer_authentication/lib/user_repository.dart
examples/bearer_authentication/pubspec.yaml
examples/bearer_authentication/pubspec_overrides.yaml
examples/bearer_authentication/routes/auth/_middleware.dart
examples/bearer_authentication/routes/auth/index.dart
examples/bearer_authentication/routes/users/[id].dart
examples/bearer_authentication/routes/users/_middleware.dart
examples/bearer_authentication/routes/users/index.dart
examples/bearer_authentication/test/lib/session_repository_test.dart
examples/bearer_authentication/test/lib/user_repository_test.dart
examples/bearer_authentication/test/routes/auth/index_test.dart
examples/bearer_authentication/test/routes/users/[id]_test.dart
examples/bearer_authentication/test/routes/users/index_test.dart

**READY**
Adds a simple example of how a bearer authentication can work with the dart frog auth package.
In a next PR, I will work in a more "full blown" tutorial, using the bearer token+jwt to make a full auth system.

feat: adding bearer authentication example

---

packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/lib/src/dev_server_runner/dev_server_runner.dart
packages/dart_frog_cli/lib/src/runtime_compatibility.dart
packages/dart_frog_cli/test/src/commands/dev/dev_test.dart
packages/dart_frog_cli/test/src/commands/dev_server_runner/dev_server_runner_test.dart

This PR comes after #729. 
Unlike #729, this is a significant change in how the dev server is/can be managed by the dev command and other tools. 
It introduces two new methods:
- Reload: After the dev server starts, re-run the codegen
- Stop: Stops the dev server. To keep the same pattern as found on `dart:io `(`Process`), `dart:async` (`Completer`) and in the flutter daemon, when completed, the dev server instance cannot be restarted.
This is part of https://github.com/VeryGoodOpenSource/dart_frog/issues/705

feat(dart_frog_cli): add devserver lifecycle

---

extensions/vscode/package.json

**READY**
Changes the when clause to allow new commands to prompt when _routes_ directory is selected.
> Note: This is a quick fix, ideally we would check if the project is actually a Dart Frog project. This will be amended in a different Pull Request where we will also restrict commands showing if the window is not opened at the root of a Dart Frog project.
After:
https://github.com/VeryGoodOpenSource/dart_frog/assets/44524995/4033e079-ed46-44bb-a2b1-483ef51a121c
Before:
https://github.com/VeryGoodOpenSource/dart_frog/assets/44524995/2c1178e5-4bf8-4fc0-ab8c-4a0c0aeaede5

fix(vscode): alter when command menu palette commands show

---

bricks/create_dart_frog/__brick__/pubspec.yaml
bricks/create_dart_frog/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_new/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/pubspec.yaml
docs/docs/tutorials/todos.md
examples/basic_authentication/pubspec.yaml
examples/bearer_authentication/pubspec.yaml
examples/counter/pubspec.yaml
examples/echo/pubspec.yaml
examples/hello_world/pubspec.yaml
examples/kitchen_sink/pubspec.yaml
examples/todos/packages/in_memory_todos_data_source/pubspec.yaml
examples/todos/packages/todos_data_source/pubspec.yaml
examples/todos/pubspec.yaml
examples/web_socket_counter/pubspec.yaml
extensions/vscode/src/test/suite/utils/dart-frog-structure.test.ts
packages/dart_frog/pubspec.yaml
packages/dart_frog_auth/pubspec.yaml
packages/dart_frog_cli/pubspec.yaml
packages/dart_frog_gen/pubspec.yaml
packages/dart_frog_web_socket/pubspec.yaml

**READY**
- chore(deps): bump `package:mocktail` and `very_good_analysis`

chore(deps): bump `package:mocktail` and `very_good_analysis`

---

packages/dart_frog_cli/e2e/test/new_test.dart
packages/dart_frog_cli/lib/src/command.dart
packages/dart_frog_cli/lib/src/command_runner.dart
packages/dart_frog_cli/lib/src/commands/dev/dev.dart
packages/dart_frog_cli/test/src/command_runner_test.dart
packages/dart_frog_cli/test/src/commands/daemon/daemon_test.dart
packages/dart_frog_cli/test/src/commands/dev/dev_test.dart
packages/dart_frog_cli/test/src/commands/list/list_test.dart
packages/dart_frog_cli/test/src/commands/new/new_test.dart
packages/dart_frog_cli/test/src/commands/update/update_test.dart

**READY**
test(dart_frog_cli): mock stdin in the ommand run level
For some reason, using io's std directly on gh action causes the build to fail on random places. For example here:
This pr ensures stdin is always mocked

test(dart_frog_cli): mock stdin in the command run level

---

extensions/vscode/src/daemon/dart-frog-daemon.ts
extensions/vscode/src/daemon/index.ts
extensions/vscode/src/test/suite/daemon/dart-frog-daemon.test.ts

**READY**
Defines a `DartFrogDeamon` singleton. The `DartFrogDeamon` will have methods to send and listen to messages (in upcoming PR) to the running process and more.
The singleton will be used to access it upon command calls made by the user of the extension since it isn't possible to inject it through on user calls (such as a call from the command palette).
In addition, only a single `DartFrogDeamon` is only ever needed, since it can support multiple Dart Frog projects.

feat(vscode): define singleton DartFrogDeamon

---

examples/kitchen_sink/test/routes/photos/upload_test.dart
examples/kitchen_sink/test/routes/projects/index_test.dart
packages/dart_frog_cli/e2e/test/daemon/dev_server_domain_test.dart
packages/dart_frog_cli/lib/src/commands/create/create.dart
packages/dart_frog_cli/test/src/commands/dev_server_runner/dev_server_runner_test.dart
packages/dart_frog_cli/test/src/commands/new/new_test.dart
packages/dart_frog_web_socket/test/src/web_socket_handler_test.dart

**READY**
Increases the timeout to fix e2e on macos and apply dart lint fixes

fix: e2e tests and lint fixes

---

extensions/vscode/package.json
extensions/vscode/src/commands/debug-dev-server.ts
extensions/vscode/src/commands/index.ts
extensions/vscode/src/extension.ts
extensions/vscode/src/test/suite/commands/debug-dev-server.test.ts

**READY**
Allows attaching a development server to Dart's debugger via the command palette.
Changes:
- Registers debug-dev-server command
https://github.com/VeryGoodOpenSource/dart_frog/assets/44524995/75f07036-d742-41f0-aa90-8c8e12b4a365

feat(vscode): allow attaching development server to Dart debugger

---

extensions/vscode/src/code-lens/on-request-code-lens.ts
extensions/vscode/src/test/suite/code-lens/on-request-code-lens.test.ts

**READY**
Updates the Regular Expression to support long route signatures.
The Regular Expression will now ignore the RequestContext as the first parameter. @wolfenrain and I are not to worry about it. Eventually, we will replace the RegExp by analysing the AST.

fix(vscode): support CodeLens for very long route signatures

---

docs/docs/advanced/daemon.md

**READY**
Add a format warning regarding requests.
Since something as the following will succeed but only apply to the first request. This usage is considerded problematic and should not be used.
```sh
[{"id":"1","method":"dev_server.start","params":{"workingDirectory":"/Users/alestiago/Developer/workspace/oss/issues/sample","port":8080,"dartVmServicePort":8181}},{"id":"2","method":"dev_server.start","params":{"workingDirectory":"/Users/alestiago/Developer/workspace/oss/issues/sample","port":8080,"dartVmServicePort":8181}}]
```
(cc: @renancaraujo )

docs: add daemon request format warning

---

extensions/vscode/CHANGELOG.md
extensions/vscode/package-lock.json
extensions/vscode/package.json

**READY**
Release 0.2.2, see CHANGELOG.

chore(vscode): 0.2.2

---

packages/dart_frog_cli/lib/src/daemon/domain/dev_server_domain.dart
packages/dart_frog_cli/lib/src/daemon/domain/route_configuration_domain.dart
packages/dart_frog_cli/lib/src/daemon/exceptions.dart
packages/dart_frog_cli/lib/src/daemon/protocol.dart
packages/dart_frog_cli/test/src/daemon/domain/dev_server_domain_test.dart
packages/dart_frog_cli/test/src/daemon/domain/route_configuration_domain_test.dart
packages/dart_frog_cli/test/src/daemon/protocol_test.dart

**READY**
Fix #913 
`dart_frog_cli` Daemon wil now report missing parameters for `dev_server` and `route_configuration` domains

fix(dart_frog_cli): report daemon missing parameters

---

bricks/dart_frog_prod_server/hooks/lib/src/create_external_packages_folder.dart

**READY**
The `createExternalPackagesFolder` had an unused "pathContext" parameter. This Pull Requests removes it.

refactor(dart_frog_prod_server): remove unused "pathContext" parameter

---

bricks/dart_frog_prod_server/hooks/lib/src/create_bundle.dart
bricks/dart_frog_prod_server/hooks/lib/src/create_external_packages_folder.dart
bricks/dart_frog_prod_server/hooks/pre_gen.dart
bricks/dart_frog_prod_server/hooks/test/src/create_bundle_test.dart
bricks/dart_frog_prod_server/hooks/test/src/create_external_packages_folder_test.dart

**READY**
Current code has logic for build directory sparse around multiple source files (`create_bundle.dart` and `create_external_packages_folder.dart`), this Pull Request ensures that `buildDirectory` is injected. Ensuring ther is a single place with the logic (i.e.`path.join` statements with magic strings) of where the `buildDirectory` actually is.
It also renames those directories named `directory` that referred to the project directory as `projectDirectory` (more explicit).

refactor(dart_frog_prod_server): reuse buildDirectory

---

bricks/dart_frog_prod_server/hooks/lib/src/create_external_packages_folder.dart
bricks/dart_frog_prod_server/hooks/pubspec.yaml

**READY**
In preparation for #1243 
Changes:
- Refactors the logic by introducing `ExternalPathDependency` class
- Uses a type definition to avoid long type function signatures
- Copy directory paths in parallel with `Future.wait`

refactor(dart_frog_prod_server): clean `createExternalPackagesFolder` logic

---

bricks/dart_frog_prod_server/hooks/test/src/create_external_packages_folder_test.dart

**READY**
`createExternalPackagesFolder` doesn't use the `pubspec.yaml` that is being setup, it only requires the `pubspec.lock` data which is being provided as a fixture. This Pull Request removes these unnecessary statements.

test(dart_frog_prod_server): remove unnecessary pubspec.yaml setup

---

bricks/dart_frog_prod_server/hooks/lib/src/create_external_packages_folder.dart
bricks/dart_frog_prod_server/hooks/test/pubspec_locks.dart
bricks/dart_frog_prod_server/hooks/test/src/create_external_packages_folder_test.dart

**READY**
Resolves #1243 
<details>
<summary> Demonstration </summary>
https://github.com/VeryGoodOpenSource/dart_frog/assets/44524995/f1d5d3be-5622-4477-a1bd-a0b9fa0dbbb6
</details>

fix(dart_frog_prod_server): stop assuming directory name is package name when bundling

---

docs/docs/advanced/authentication.md
packages/dart_frog_auth/lib/src/dart_frog_auth.dart
packages/dart_frog_auth/test/src/dart_frog_auth_test.dart

**READY**
Adds cookie authentication to dart_frog_auth and documents its use in the documentation site. Closes #1589

feat(dart_frog_auth): add cookie authentication

---

packages/dart_frog_auth/CHANGELOG.md
packages/dart_frog_auth/pubspec.yaml

**READY**
Closes #1617. Gets 1.2.0 release for Dart Frog Auth completed.
Note: Docs site updates have been removed from this changelog.

chore(dart_frog_auth): 1.2.0

---

packages/dart_frog_cli/CHANGELOG.md
packages/dart_frog_cli/lib/src/version.dart
packages/dart_frog_cli/pubspec.yaml

**READY/IN DEVELOPMENT/HOLD**
Closes #1615. Get's the dart_frog_cli 1.2.4 release ready.
Note: docs updates have been removed from the changelog

chore(dart_frog_cli): 1.2.4

---

packages/dart_frog_cli/pubspec.yaml

**READY**
Fixes #1621. Updates `mason` for the cli to resolve the right way and pub doesn't complain.

fix: update mason version in cli

---

packages/dart_frog/CHANGELOG.md
packages/dart_frog/lib/src/response.dart
packages/dart_frog/pubspec.yaml

**READY**
Closes #1616. Get the 1.2.0 release for the main dart_frog package released.
Note: Docs updates have been removed from the changelog.

chore(dart_frog): v1.2.0

---

.github/actions/pub_publish/action.yaml
.github/workflows/publish_dart_frog.yaml
.github/workflows/publish_dart_frog_auth.yaml
.github/workflows/publish_dart_frog_cli.yaml
.github/workflows/publish_dart_frog_gen.yaml
.github/workflows/publish_dart_frog_test.yaml
.github/workflows/publish_dart_frog_web_socket.yaml

**READY**
- ci: configure automated pub publishing

ci: configure automated pub publishing

---

bricks/create_dart_frog/hooks/analysis_options.yaml
bricks/create_dart_frog/hooks/pubspec.yaml
bricks/dart_frog_dev_server/hooks/analysis_options.yaml
bricks/dart_frog_dev_server/hooks/pubspec.yaml
bricks/dart_frog_new/hooks/analysis_options.yaml
bricks/dart_frog_new/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/analysis_options.yaml
bricks/dart_frog_prod_server/hooks/lib/src/create_bundle.dart
bricks/dart_frog_prod_server/hooks/lib/src/pubspec_lock/pubspec_lock.dart
bricks/dart_frog_prod_server/hooks/pre_gen.dart
bricks/dart_frog_prod_server/hooks/pubspec.yaml
bricks/dart_frog_prod_server/hooks/test/pubspec_locks.dart
bricks/dart_frog_prod_server/hooks/test/src/pubspec_lock/pubspec_lock_test.dart
examples/todos/packages/in_memory_todos_data_source/analysis_options.yaml
examples/todos/packages/in_memory_todos_data_source/pubspec.yaml
examples/todos/packages/todos_data_source/analysis_options.yaml
examples/todos/packages/todos_data_source/pubspec.yaml
packages/dart_frog_cli/e2e/analysis_options.yaml
packages/dart_frog_cli/e2e/pubspec.yaml

**READY**
- refactor(bricks): update hook dependencies

refactor(bricks): update hook dependencies

---

docs/astro.config.mjs
docs/package-lock.json
docs/package.json

**READY**
- docs: add `/discord` redirect
- deps: upgrade astro

docs: add `/discord` redirect
